import { createHash } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { resolve } from "node:path";
import { createAuditEvent, createUuidV7 } from "@/audit/audit-event";
import { copyDocumentedEvidenceArtifacts, copyExperienceMarkdown, copyProjectMarkdown, readManagedDocumentedArtifacts, readManagedMarkdown, readResumeDocumentationSource, type CopiedLibraryContent, type LibraryCategory, type MarkdownDocument } from "@/files/evidence-library";
import { resolveAppDataPaths } from "@/files/app-data";
import { insertRecord, insertRevision, listCurrentEvidence, type EvidenceRevision } from "@/persistence/evidence-repository";
import { candidateExists, findDocumentByPath, findDocumentByPathAndDigest, findImport, insertCandidate, insertDocument, insertImport, type EvidenceLibraryDocument } from "@/persistence/evidence-library-repository";
import { applyMigrations, openDatabase } from "@/persistence/database";
import { appendAuditEvent } from "@/persistence/workspace-repository";
import { WorkspaceError } from "@/domain/workspace/types";
import { requestResumeEvidenceDocumentation, resumeEvidenceDocumenterConsentFingerprint } from "@/adapters/local-model/local-model-gateway";
import { readLocalModelGatewayConfiguration } from "@/domain/resume-generation/local-model-configuration-commands";
import { getResumeAgentSkill } from "@/domain/resume-agent/skill-registry";
type Options = { appDataRoot?: string; workspaceRoot?: string };
export type LibraryImportResult = { documentsAdded: number; candidatesAdded: number; documents: EvidenceLibraryDocument[] };
export type ExperienceProjectCollection = { name: string; category: LibraryCategory; summary: string; artifactNames: string[]; evidence: Array<Pick<EvidenceRevision, "factualText" | "reviewState"> & { reviewHandle: string }> };
const maxCandidatesPerOperation = 2000;
const hash = (text: string) => `sha256:${createHash("sha256").update(text).digest("hex")}`;
type Candidate = { factualText: string; sourceSection: string; lineNumber: number; contentDigest: string; evidenceKey?: string };
type SourceSnapshot = Awaited<ReturnType<typeof readResumeDocumentationSource>>;
function safeSection(value: string): string { return value.replace(/[\u0000-\u001f]/g, " ").replace(/\.\./g, "…").replace(/^(?:[a-z]:[\\/]|[\\/]{1,2}|file:)/i, "").replace(/\s+/g, " ").trim().slice(0, 300) || "document"; }
function candidates(document: MarkdownDocument): Candidate[] { let heading = "document"; let fence: { marker: string; length: number } | undefined; const result: Candidate[] = []; for (const [index, raw] of document.text.split(/\r?\n/).entries()) { const text = raw.trim(); const fenceMatch = /^(`{3,}|~{3,})(.*)$/.exec(text); if (fence) { if (fenceMatch && fenceMatch[1][0] === fence.marker && fenceMatch[1].length >= fence.length && !fenceMatch[2].trim()) fence = undefined; continue; } if (fenceMatch) { fence = { marker: fenceMatch[1][0], length: fenceMatch[1].length }; continue; } if (!text) continue; const match = /^(#{1,6})\s+(.+)$/.exec(text); if (match) { heading = safeSection(match[2]); continue; } const factualText = text.replace(/^[-*+]\s+/, "").replace(/^\d+[.)]\s+/, "").trim(); if (!factualText || factualText.length > 5000 || /[\u0000-\u001f]/.test(factualText)) continue; result.push({ factualText, sourceSection: `${heading}, line ${index + 1}`, lineNumber: index + 1, contentDigest: hash(factualText) }); if (result.length > maxCandidatesPerOperation) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "One Markdown document has too many evidence candidates.", "Split the document into smaller resume-evidence files and try again."); } return result; }
function prepare(documents: MarkdownDocument[]): Array<{ document: MarkdownDocument; candidates: Candidate[] }> { const prepared = documents.map((document) => ({ document, candidates: candidates(document) })); if (prepared.reduce((total, value) => total + value.candidates.length, 0) > maxCandidatesPerOperation) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "This library operation has too many evidence candidates.", "Import or refresh fewer Markdown documents at a time."); return prepared; }
const containsAbsolutePath = (value: string) => /(?:\b[a-z]:[\\/]|\\\\|\bfile:|(?:^|[\s[(])\/(?:[^/\s]+\/)+)/im.test(value);
function nearestHeading(text: string, line: number): string { let heading = "document"; for (const raw of text.split(/\r?\n/).slice(0, line)) { const match = /^#{1,6}\s+(.+)$/.exec(raw.trim()); if (match) heading = safeSection(match[1]); } return heading; }
function validateSnapshotFact(snapshot: SourceSnapshot, sourcePath: string, sourceHeading: string, line: number, fact: string): void { const source = snapshot.files.find((file) => file.path === sourcePath); const sourceLine = source?.text.split(/\r?\n/)[line - 1]; if (!source || !sourceLine || nearestHeading(source.text, line) !== safeSection(sourceHeading) || !sourceLine.includes(fact)) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "A generated evidence item is not grounded in the selected source snapshot.", "Run the local documentation action again after reviewing the selected folder."); }
function documentedCandidates(document: MarkdownDocument, snapshot?: SourceSnapshot): Candidate[] {
  if (!document.libraryPath.endsWith("/resume-evidence.md")) return [];
  if (!/^# Resume Evidence \(Proposed \/ Unreviewed\)/m.test(document.text)) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "The generated evidence document is not a proposed review artifact.", "Run the documentation skill again into a new empty output folder.");
  if (/^- No supported evidence items found\.\s*$/m.test(document.text)) return [];
  const result: Candidate[] = []; const blocks = [...document.text.matchAll(/^### (E-\d{3})\s*$([\s\S]*?)(?=^### E-\d{3}\s*$|(?![\s\S]))/gm)]; const evidenceKeys = new Set<string>();
  for (const block of blocks) {
    const body = block[2]; const fact = /^- Fact:\s*(.+?)\s*$/m.exec(body)?.[1]?.trim(); const provenance = /^- Provenance:\s*\[?([^\]\r\n]+)\]?\s*$/m.exec(body)?.[1]?.replaceAll("`", "").trim(); const unknowns = /^- Explicit unknowns:\s*.+\S\s*$/m.test(body); const status = /^- Status:\s*Proposed\s*\/\s*unreviewed\s*$/mi.test(body);
    const provenanceMatch = provenance && /^([^\\/][^\\]*?),\s*(.+?),\s*line\s+([1-9]\d*)$/i.exec(provenance);
    if (!fact || fact.length > 5000 || /[\u0000-\u001f]/.test(fact) || containsAbsolutePath(fact) || !unknowns || !status || !provenanceMatch || evidenceKeys.has(block[1])) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "A generated evidence item is malformed or ambiguous.", "Run the documentation skill again and import a new output folder.");
    const [, sourcePath, sourceHeading, line] = provenanceMatch;
    if (sourcePath.includes("..") || sourcePath.includes("\\") || /^(?:[a-z]:|\/|\\\\|[a-z][a-z0-9+.-]*:)/i.test(sourcePath) || !sourceHeading.trim()) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "A generated evidence item has unsafe provenance.", "Run the documentation skill again and import a new output folder.");
    if (snapshot) validateSnapshotFact(snapshot, sourcePath, sourceHeading, Number(line), fact);
    const lineNumber = document.text.slice(0, block.index).split(/\r?\n/).length + body.slice(0, body.indexOf(fact)).split(/\r?\n/).length - 1;
    evidenceKeys.add(block[1]); result.push({ factualText: fact, sourceSection: safeSection(`${sourcePath}, ${sourceHeading}, line ${line}`), lineNumber, contentDigest: hash(`${fact}\n${sourcePath}\n${sourceHeading}\n${line}`), evidenceKey: block[1] });
  }
  if (!blocks.length || result.length !== blocks.length) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "The generated evidence document has no valid evidence items.", "Run the documentation skill again and import a new output folder.");
  return result;
}
function validateReviewArtifacts(documents: MarkdownDocument[], evidenceKeys: Set<string>): void { const overview = documents.find((document) => document.libraryPath.endsWith("/project-overview.md")); const bullets = documents.find((document) => document.libraryPath.endsWith("/resume-bullet-candidates.md")); if (!overview || !bullets || !/^# Project Overview \(Proposed \/ Unreviewed\)/m.test(overview.text) || !/^# Resume Bullet Candidates \(Proposed \/ Unreviewed\)/m.test(bullets.text) || containsAbsolutePath(overview.text) || containsAbsolutePath(bullets.text)) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "The generated review artifacts do not match the safe documentation contract.", "Run the local documentation action again."); const blocks = [...bullets.text.matchAll(/^### (B-\d{3})\s*$([\s\S]*?)(?=^### B-\d{3}\s*$|(?![\s\S]))/gm)]; if (!evidenceKeys.size && /^- No supported bullet candidates found\.\s*$/m.test(bullets.text)) return; const bulletKeys = new Set<string>(); for (const block of blocks) { const body = block[2]; const candidate = /^- Candidate:\s*(.+?)\s*$/m.exec(body)?.[1]?.trim(); const support = /^- Supporting evidence:\s*((?:E-\d{3})(?:,\s*E-\d{3})*)\s*$/m.exec(body)?.[1]?.split(/,\s*/); if (!candidate || containsAbsolutePath(candidate) || bulletKeys.has(block[1]) || !support?.length || support.some((id) => !evidenceKeys.has(id)) || !/^- Explicit unknowns:\s*.+\S\s*$/m.test(body) || !/^- Status:\s*Proposed\s*\/\s*unreviewed;\s*not claim-eligible\s*$/mi.test(body)) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "A generated bullet candidate is malformed or unsupported.", "Run the local documentation action again."); bulletKeys.add(block[1]); } if (evidenceKeys.size && !blocks.length) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "The generated bullet candidates are incomplete.", "Run the local documentation action again."); }
function prepareDocumented(documents: MarkdownDocument[], snapshot?: SourceSnapshot): Array<{ document: MarkdownDocument; candidates: Candidate[] }> { const prepared = documents.map((document) => ({ document, candidates: documentedCandidates(document, snapshot) })); const evidenceDocuments = prepared.filter((item) => item.document.libraryPath.endsWith("/resume-evidence.md")); const evidenceKeys = new Set(prepared.flatMap((item) => item.candidates.map((candidate) => candidate.evidenceKey).filter((key): key is string => Boolean(key)))); if (evidenceDocuments.length !== 1 || prepared.reduce((total, value) => total + value.candidates.length, 0) > maxCandidatesPerOperation) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "The generated review documents contain an invalid amount of evidence.", "Run the documentation skill again and import a new output folder."); validateReviewArtifacts(documents, evidenceKeys); return prepared; }
function revision(evidenceId: string, candidate: Candidate, document: MarkdownDocument): EvidenceRevision { return { id: createUuidV7(), evidenceId, revisionNumber: 1, origin: "extracted", sourceDocument: document.libraryPath, sourceSection: candidate.sourceSection, factualText: candidate.factualText, reviewState: "unreviewed", createdAt: new Date().toISOString(), contentDigest: candidate.contentDigest }; }
function saveDocuments(database: ReturnType<typeof openDatabase>, prepared: ReturnType<typeof prepare>, importId: string): LibraryImportResult { let documentsAdded = 0; let candidatesAdded = 0; const stored: EvidenceLibraryDocument[] = []; for (const value of prepared) { const latest = findDocumentByPath(database, value.document.libraryPath); let record = findDocumentByPathAndDigest(database, value.document.libraryPath, value.document.contentDigest); if (!record) { record = { id: createUuidV7(), category: value.document.category, libraryPath: value.document.libraryPath, contentDigest: value.document.contentDigest, importedAt: new Date().toISOString() }; insertDocument(database, { ...record, importId }); documentsAdded += 1; } else if (!latest || latest.id !== record.id) { documentsAdded += 0; } stored.push(record); for (const candidate of value.candidates) { if (candidateExists(database, record.id, candidate.sourceSection, candidate.lineNumber, candidate.contentDigest)) continue; const item = revision(createUuidV7(), candidate, value.document); insertRecord(database, item.evidenceId, item.createdAt); insertRevision(database, item); insertCandidate(database, { documentId: record.id, sourceSection: candidate.sourceSection, lineNumber: candidate.lineNumber, contentDigest: candidate.contentDigest, evidenceRevisionId: item.id }); appendAuditEvent(database, createAuditEvent({ actor: "local-os-user", action: "evidence.library_candidate_created", outcome: "success", entityId: item.id, contentHash: item.contentDigest })); candidatesAdded += 1; } } return { documentsAdded, candidatesAdded, documents: stored }; }
async function persist(options: Options, source: { category: "project" | "experience" | "refresh"; identity: string; digest: string }, documents: MarkdownDocument[]): Promise<LibraryImportResult> { const prepared = prepare(documents); const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); database.exec("BEGIN IMMEDIATE;"); try { const existing = findImport(database, source.identity, source.digest); if (existing && source.category !== "refresh") throw new WorkspaceError("EVIDENCE_LIBRARY_DUPLICATE", "That source has already been added to the evidence library.", "Refresh the library or choose a different source folder."); const importId = existing?.id ?? createUuidV7(); if (!existing) insertImport(database, { id: importId, category: source.category, sourceIdentity: source.identity, sourceDigest: source.digest, createdAt: new Date().toISOString() }); const result = saveDocuments(database, prepared, importId); appendAuditEvent(database, createAuditEvent({ actor: "local-os-user", action: "evidence.library_imported", outcome: "success", entityId: importId, contentHash: source.digest })); database.exec("COMMIT;"); return result; } catch (error) { database.exec("ROLLBACK;"); throw error; } } finally { database.close(); } }
async function persistCopied(input: Options, source: { category: "project" | "experience"; identity: string; digest: string }, copied: CopiedLibraryContent): Promise<LibraryImportResult> { try { return await persist(input, source, copied.documents); } catch (error) { await copied.cleanup(); throw error; } }
async function persistDocumentedCopied(input: Options, source: { category: "project" | "experience"; identity: string; digest: string }, copied: CopiedLibraryContent, snapshot?: SourceSnapshot): Promise<LibraryImportResult> { const prepared = prepareDocumented(copied.documents, snapshot); const paths = await resolveAppDataPaths(input.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); database.exec("BEGIN IMMEDIATE;"); try { const existing = findImport(database, source.identity, source.digest); if (existing) throw new WorkspaceError("EVIDENCE_LIBRARY_DUPLICATE", "That documented item has already been imported.", "Review the existing collection item or choose a different documented item."); const importId = createUuidV7(); insertImport(database, { id: importId, category: source.category, sourceIdentity: source.identity, sourceDigest: source.digest, createdAt: new Date().toISOString() }); const result = saveDocuments(database, prepared, importId); appendAuditEvent(database, createAuditEvent({ actor: "local-os-user", action: "evidence.library_imported", outcome: "success", entityId: importId, contentHash: source.digest })); database.exec("COMMIT;"); return result; } catch (error) { database.exec("ROLLBACK;"); throw error; } } catch (error) { await copied.cleanup(); throw error; } finally { database.close(); } }
export async function addProjectToEvidenceLibrary(input: Options & { sourceDirectory: string; name?: string }): Promise<LibraryImportResult> { const copied = await copyProjectMarkdown(input.sourceDirectory, input.name, input.workspaceRoot); return persistCopied(input, { category: "project", identity: `project:${hash(resolve(input.sourceDirectory))}`, digest: copied.sourceDigest }, copied); }
export async function addExperienceToEvidenceLibrary(input: Options & { name: string; markdown?: string; sourceFile?: string }): Promise<LibraryImportResult> { const copied = await copyExperienceMarkdown(input); return persistCopied(input, { category: "experience", identity: `experience:${input.name.trim().toLowerCase()}`, digest: copied.sourceDigest }, copied); }
export async function importDocumentedEvidenceArtifacts(input: Options & { outputDirectory: string; name: string; category: LibraryCategory; sourceSnapshot?: SourceSnapshot }): Promise<LibraryImportResult> { const copied = await copyDocumentedEvidenceArtifacts(input); return persistDocumentedCopied(input, { category: input.category, identity: `documented:${input.category}:${input.name.trim().toLowerCase()}`, digest: copied.sourceDigest }, copied, input.sourceSnapshot); }
export async function documentResumeEvidenceFolder(input: Options & { sourceDirectory: string; name: string; category: LibraryCategory; disclosed: boolean }): Promise<LibraryImportResult> {
  const skill = getResumeAgentSkill("resume.document-source-folder"); if (!skill.requiresConsent || !skill.writableRoots.includes("private-staging-output") || skill.prohibitedOperations.some((operation) => !["network", "shell", "watchers", "background-jobs", "credentials", "source-mutation", "unregistered-skills", "external-developer-prompts"].includes(operation))) throw new WorkspaceError("EVIDENCE_DOCUMENTER_INVALID", "The local documentation skill policy is unavailable.", "Review the configured local documentation skill and try again.");
  if (!input.disclosed) throw new WorkspaceError("EVIDENCE_DOCUMENTER_INVALID", "Confirm that this selected folder may be inspected by your configured local AI.", "Select the local documentation consent checkbox and try again.");
  const source = await readResumeDocumentationSource(input.sourceDirectory, input.workspaceRoot); const configured = await readLocalModelGatewayConfiguration({ appDataRoot: input.appDataRoot }); const request = { connection: { configurationRevisionId: configured.id, configurationDigest: configured.configurationDigest, modelIdentifier: configured.modelIdentifier, token: configured.token }, category: input.category, sourceDigest: source.sourceDigest, files: source.files, consentFingerprint: "" } as const; const consentFingerprint = resumeEvidenceDocumenterConsentFingerprint(request); const output = await requestResumeEvidenceDocumentation({ ...request, consentFingerprint }); const currentSource = await readResumeDocumentationSource(input.sourceDirectory, input.workspaceRoot); if (currentSource.sourceDigest !== source.sourceDigest) throw new WorkspaceError("EVIDENCE_DOCUMENTER_INVALID", "The selected folder changed while documentation was running.", "Review the folder and run local documentation again."); const paths = await resolveAppDataPaths(input.appDataRoot); const staging = await mkdtemp(join(paths.root, "documenter-staging-"));
  try { for (const [name, content] of Object.entries(output.artifacts)) await writeFile(join(staging, name), content, { encoding: "utf8", flag: "wx" }); return await importDocumentedEvidenceArtifacts({ appDataRoot: input.appDataRoot, workspaceRoot: input.workspaceRoot, outputDirectory: staging, name: input.name, category: input.category, sourceSnapshot: source }); } finally { await rm(staging, { recursive: true, force: true }).catch(() => undefined); }
}
export async function refreshEvidenceLibrary(input: Options = {}): Promise<LibraryImportResult> { const documents = await readManagedMarkdown(input.workspaceRoot); const digest = hash(documents.map((document) => `${document.libraryPath}:${document.contentDigest}`).sort().join("\n")); return persist(input, { category: "refresh", identity: `refresh:${digest}`, digest }, documents); }
export async function listEvidenceLibrary(options: Options = {}): Promise<EvidenceLibraryDocument[]> { const documents = await readManagedMarkdown(options.workspaceRoot).catch((error) => { if (error instanceof WorkspaceError && error.code === "EVIDENCE_LIBRARY_EMPTY") return []; throw error; }); if (!documents.length) return []; const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); return documents.flatMap((document) => { const record = findDocumentByPathAndDigest(database, document.libraryPath, document.contentDigest); return record ? [record] : []; }); } finally { database.close(); } }
export function summaryFromProjectOverview(markdown: string): string {
  let fence: { marker: string; length: number } | undefined; const paragraphs: string[] = []; let current: string[] = []; const lines = markdown.replace(/<!--[\s\S]*?-->/g, "").split(/\r?\n/); const frontMatterEnd = lines[0]?.trim() === "---" ? lines.slice(1).findIndex((line) => line.trim() === "---") : -1; const content = frontMatterEnd >= 0 ? lines.slice(frontMatterEnd + 2) : lines[0]?.trim() === "---" ? [] : lines;
  const push = () => { const text = current.join(" ").replace(/^[-*+]\s+/, "").replace(/^\d+[.)]\s+/, "").replace(/\s+/g, " ").trim(); if (text) paragraphs.push(text); current = []; };
  for (const raw of content) { if (/^\s*<!--.*-->\s*$/.test(raw)) continue; const fenceMatch = /^ {0,3}(`{3,}|~{3,})(.*)$/.exec(raw); if (fence) { if (fenceMatch && fenceMatch[1][0] === fence.marker && fenceMatch[1].length >= fence.length && !fenceMatch[2].trim()) fence = undefined; continue; } if (fenceMatch) { push(); fence = { marker: fenceMatch[1][0], length: fenceMatch[1].length }; continue; } if (!raw.trim() || /^\s*#{1,6}\s+/.test(raw)) { push(); continue; } current.push(raw.trim()); }
  push(); const sentence = paragraphs[0]?.match(/^(.+?[.!?])(?:\s|$)/)?.[1] ?? paragraphs[0]; if (!sentence) return "No summary found yet."; return sentence.length <= 240 ? sentence : `${sentence.slice(0, 239).replace(/\s+\S*$/, "").trimEnd()}…`;
}
export function collectionReviewHandle(evidenceId: string, revisionId: string): string { return hash(`review-handle:${evidenceId}:${revisionId}`); }
export async function resolveCollectionReviewHandle(handle: string, options: Options = {}): Promise<{ evidenceId: string; expectedRevisionId: string }> { if (!/^sha256:[a-f0-9]{64}$/.test(handle)) throw new WorkspaceError("EVIDENCE_INVALID", "The requested evidence review item is unavailable.", "Refresh the collection and try the individual review action again."); const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); const item = listCurrentEvidence(database).find((candidate) => collectionReviewHandle(candidate.evidenceId, candidate.id) === handle); if (!item) throw new WorkspaceError("EVIDENCE_INVALID", "The requested evidence review item is unavailable.", "Refresh the collection and try the individual review action again."); return { evidenceId: item.evidenceId, expectedRevisionId: item.id }; } finally { database.close(); } }
export async function listExperienceProjectCollection(options: Options = {}): Promise<ExperienceProjectCollection[]> { const groups = await readManagedDocumentedArtifacts(options.workspaceRoot); if (!groups.length) return []; const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); const evidence = listCurrentEvidence(database); return groups.map((group) => { const overview = group.documents.find((document) => document.libraryPath.endsWith("/project-overview.md")); const evidenceDocument = group.documents.find((document) => document.libraryPath.endsWith("/resume-evidence.md")); return { name: group.name, category: group.category, summary: summaryFromProjectOverview(overview?.text ?? ""), artifactNames: group.documents.map((document) => document.libraryPath.split("/").at(-1)!).sort(), evidence: evidence.filter((item) => item.sourceDocument === evidenceDocument?.libraryPath).map(({ id, evidenceId, factualText, reviewState }) => ({ factualText, reviewState, reviewHandle: collectionReviewHandle(evidenceId, id) })) }; }); } finally { database.close(); } }
export async function recordEvidenceLibraryFailure(options: Options = {}): Promise<void> { const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); appendAuditEvent(database, createAuditEvent({ actor: "local-os-user", action: "evidence.library_failed", outcome: "failure" })); } finally { database.close(); } }
