import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { isAbsolute, relative, resolve } from "node:path";
import { createAuditEvent, createUuidV7 } from "@/audit/audit-event";
import { resolveAppDataPaths } from "@/files/app-data";
import { applyMigrations, openDatabase } from "@/persistence/database";
import { currentRevision, insertRecord, insertRevision, listApprovedEvidence, listCurrentEvidence, type EvidenceRevision } from "@/persistence/evidence-repository";
import { appendAuditEvent } from "@/persistence/workspace-repository";
import { WorkspaceError } from "@/domain/workspace/types";

type Options = { appDataRoot?: string };
type Add = Options & { factualText: string; sourceDocument: string; sourceSection: string };
type Mutate = Options & { evidenceId: string; expectedRevisionId: string };
const hash = (text: string) => `sha256:${createHash("sha256").update(text).digest("hex")}`;
function validate(value: string, label: string): string { const result = value.trim(); if (!result || result.length > 5000 || /[\u0000-\u001f]/.test(result) || /^(?:[a-z]:[\\/]|[\\/]{1,2}|file:)/i.test(result) || result.includes("..")) throw new WorkspaceError("EVIDENCE_INVALID", `The ${label} needs a safe, non-empty value.`, "Correct the indicated evidence field and try again."); return result; }
function revision(evidenceId: string, previous: EvidenceRevision | undefined, changes: Partial<Pick<EvidenceRevision, "factualText" | "reviewState" | "origin" | "sourceDocument" | "sourceSection">> = {}): EvidenceRevision { const factualText = changes.factualText ?? previous?.factualText ?? ""; return { id: createUuidV7(), evidenceId, revisionNumber: (previous?.revisionNumber ?? 0) + 1, origin: changes.origin ?? previous?.origin ?? "user_entered", sourceDocument: changes.sourceDocument ?? previous?.sourceDocument ?? "", sourceSection: changes.sourceSection ?? previous?.sourceSection ?? "", factualText, reviewState: changes.reviewState ?? "unreviewed", createdAt: new Date().toISOString(), contentDigest: hash(factualText) }; }
async function transact<T>(options: Options, work: (database: ReturnType<typeof openDatabase>) => T): Promise<T> { const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); database.exec("BEGIN IMMEDIATE;"); try { const result = work(database); database.exec("COMMIT;"); return result; } catch (error) { database.exec("ROLLBACK;"); throw error; } } finally { database.close(); } }
function append(database: ReturnType<typeof openDatabase>, action: Parameters<typeof createAuditEvent>[0]["action"], item: EvidenceRevision): void { appendAuditEvent(database, createAuditEvent({ actor: "local-os-user", action, outcome: "success", entityId: item.id, contentHash: item.contentDigest })); }
export function addUnreviewedEvidenceInTransaction(database: ReturnType<typeof openDatabase>, input: { factualText: string; sourceDocument: string; sourceSection: string; origin?: EvidenceRevision["origin"] }): EvidenceRevision { const factualText = validate(input.factualText, "factual text"); const sourceDocument = validate(input.sourceDocument, "source document"); const sourceSection = validate(input.sourceSection, "source section"); const evidenceId = createUuidV7(); const item = revision(evidenceId, undefined, { factualText, sourceDocument, sourceSection, origin: input.origin }); insertRecord(database, evidenceId, item.createdAt); insertRevision(database, item); append(database, "evidence.added", item); return item; }
export async function addManualEvidence(input: Add): Promise<EvidenceRevision> { return transact(input, (db) => addUnreviewedEvidenceInTransaction(db, input)); }
async function mutate(input: Mutate, action: Parameters<typeof createAuditEvent>[0]["action"], state: EvidenceRevision["reviewState"], factualText?: string): Promise<EvidenceRevision> { return transact(input, (db) => { const previous = currentRevision(db, input.evidenceId); if (!previous) throw new WorkspaceError("EVIDENCE_NOT_FOUND", "That evidence item is unavailable.", "Refresh the Candidate Profile and try again."); if (previous.id !== input.expectedRevisionId) throw new WorkspaceError("EVIDENCE_STALE", "That evidence item changed before your action completed.", "Refresh the Candidate Profile, review the latest revision, and try again."); if (previous.reviewState === "removed") throw new WorkspaceError("EVIDENCE_INVALID", "Removed evidence cannot be changed.", "Add new evidence if it needs review again."); const item = revision(input.evidenceId, previous, { factualText, reviewState: state }); insertRevision(db, item, undefined, previous.id); append(db, action, item); return item; }); }
export const approveEvidence = (input: Mutate) => mutate(input, "evidence.approved", "approved");
export const rejectEvidence = (input: Mutate) => mutate(input, "evidence.rejected", "rejected");
export const removeEvidence = (input: Mutate) => mutate(input, "evidence.removed", "removed");
export const editEvidence = (input: Mutate & { factualText: string }) => mutate(input, "evidence.edited", "unreviewed", validate(input.factualText, "factual text"));
export async function listClaimEligibleEvidence(options: Options = {}): Promise<EvidenceRevision[]> { return transact(options, (db) => listApprovedEvidence(db)); }
export async function listEvidence(options: Options = {}): Promise<EvidenceRevision[]> { return transact(options, (db) => listCurrentEvidence(db)); }
export async function recordEvidenceFailure(): Promise<void> { await transact({}, (db) => { appendAuditEvent(db, createAuditEvent({ actor: "local-os-user", action: "evidence.failed", outcome: "failure" })); }); }
export async function extractEvidenceFromBaseResume(input: Options & { baseResumeId: string }): Promise<EvidenceRevision[]> { const paths = await resolveAppDataPaths(input.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); const base = database.prepare("SELECT primary_filename, storage_location FROM base_resumes WHERE id = ?").get(input.baseResumeId) as { primary_filename: string; storage_location: string } | undefined; if (!base) throw new WorkspaceError("EVIDENCE_BASE_RESUME_REQUIRED", "Choose an imported Base Resume before extracting facts.", "Import or select a Base Resume, then try again."); const filePath = resolve(paths.root, base.storage_location); const relativePath = relative(paths.root, filePath); if (isAbsolute(relativePath) || relativePath.startsWith("..")) throw new WorkspaceError("EVIDENCE_INVALID", "The imported Base Resume location is unavailable.", "Review local workspace storage, then try again."); const text = await readFile(filePath, "utf8"); const lines = text.split(/\r?\n/).map((line, index) => ({ text: line.trim(), index })).filter((line) => line.text.length > 0 && line.text.length <= 5000 && !/[\u0000-\u001f]/.test(line.text)).slice(0, 100); if (!lines.length) throw new WorkspaceError("EVIDENCE_INVALID", "No reviewable facts were found in that Base Resume.", "Add evidence manually or review the imported Base Resume."); database.exec("BEGIN IMMEDIATE;"); try { const items = lines.map((line) => { const evidenceId = createUuidV7(); const item = { ...revision(evidenceId, undefined), origin: "extracted" as const, sourceDocument: base.primary_filename, sourceSection: `line ${line.index + 1}`, factualText: line.text, contentDigest: hash(line.text) }; insertRecord(database, evidenceId, item.createdAt); insertRevision(database, item, input.baseResumeId); append(database, "evidence.extracted", item); return item; }); database.exec("COMMIT;"); return items; } catch (error) { database.exec("ROLLBACK;"); throw error; } } finally { database.close(); } }
