import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { createAuditEvent, createUuidV7 } from "@/audit/audit-event";
import { copyExperienceMarkdown, copyProjectMarkdown, readManagedMarkdown, type CopiedLibraryContent, type MarkdownDocument } from "@/files/evidence-library";
import { resolveAppDataPaths } from "@/files/app-data";
import { insertRecord, insertRevision, type EvidenceRevision } from "@/persistence/evidence-repository";
import { candidateExists, findDocumentByPath, findDocumentByPathAndDigest, findImport, insertCandidate, insertDocument, insertImport, type EvidenceLibraryDocument } from "@/persistence/evidence-library-repository";
import { applyMigrations, openDatabase } from "@/persistence/database";
import { appendAuditEvent } from "@/persistence/workspace-repository";
import { WorkspaceError } from "@/domain/workspace/types";
type Options = { appDataRoot?: string; workspaceRoot?: string };
export type LibraryImportResult = { documentsAdded: number; candidatesAdded: number; documents: EvidenceLibraryDocument[] };
const maxCandidatesPerOperation = 2000;
const hash = (text: string) => `sha256:${createHash("sha256").update(text).digest("hex")}`;
type Candidate = { factualText: string; sourceSection: string; lineNumber: number; contentDigest: string };
function safeSection(value: string): string { return value.replace(/[\u0000-\u001f]/g, " ").replace(/\.\./g, "…").replace(/^(?:[a-z]:[\\/]|[\\/]{1,2}|file:)/i, "").replace(/\s+/g, " ").trim().slice(0, 300) || "document"; }
function candidates(document: MarkdownDocument): Candidate[] { let heading = "document"; let fence: { marker: string; length: number } | undefined; const result: Candidate[] = []; for (const [index, raw] of document.text.split(/\r?\n/).entries()) { const text = raw.trim(); const fenceMatch = /^(`{3,}|~{3,})(.*)$/.exec(text); if (fence) { if (fenceMatch && fenceMatch[1][0] === fence.marker && fenceMatch[1].length >= fence.length && !fenceMatch[2].trim()) fence = undefined; continue; } if (fenceMatch) { fence = { marker: fenceMatch[1][0], length: fenceMatch[1].length }; continue; } if (!text) continue; const match = /^(#{1,6})\s+(.+)$/.exec(text); if (match) { heading = safeSection(match[2]); continue; } const factualText = text.replace(/^[-*+]\s+/, "").replace(/^\d+[.)]\s+/, "").trim(); if (!factualText || factualText.length > 5000 || /[\u0000-\u001f]/.test(factualText)) continue; result.push({ factualText, sourceSection: `${heading}, line ${index + 1}`, lineNumber: index + 1, contentDigest: hash(factualText) }); if (result.length > maxCandidatesPerOperation) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "One Markdown document has too many evidence candidates.", "Split the document into smaller resume-evidence files and try again."); } return result; }
function prepare(documents: MarkdownDocument[]): Array<{ document: MarkdownDocument; candidates: Candidate[] }> { const prepared = documents.map((document) => ({ document, candidates: candidates(document) })); if (prepared.reduce((total, value) => total + value.candidates.length, 0) > maxCandidatesPerOperation) throw new WorkspaceError("EVIDENCE_LIBRARY_INVALID", "This library operation has too many evidence candidates.", "Import or refresh fewer Markdown documents at a time."); return prepared; }
function revision(evidenceId: string, candidate: Candidate, document: MarkdownDocument): EvidenceRevision { return { id: createUuidV7(), evidenceId, revisionNumber: 1, origin: "extracted", sourceDocument: document.libraryPath, sourceSection: candidate.sourceSection, factualText: candidate.factualText, reviewState: "unreviewed", createdAt: new Date().toISOString(), contentDigest: candidate.contentDigest }; }
function saveDocuments(database: ReturnType<typeof openDatabase>, prepared: ReturnType<typeof prepare>, importId: string): LibraryImportResult { let documentsAdded = 0; let candidatesAdded = 0; const stored: EvidenceLibraryDocument[] = []; for (const value of prepared) { const latest = findDocumentByPath(database, value.document.libraryPath); let record = findDocumentByPathAndDigest(database, value.document.libraryPath, value.document.contentDigest); if (!record) { record = { id: createUuidV7(), category: value.document.category, libraryPath: value.document.libraryPath, contentDigest: value.document.contentDigest, importedAt: new Date().toISOString() }; insertDocument(database, { ...record, importId }); documentsAdded += 1; } else if (!latest || latest.id !== record.id) { documentsAdded += 0; } stored.push(record); for (const candidate of value.candidates) { if (candidateExists(database, record.id, candidate.sourceSection, candidate.lineNumber, candidate.contentDigest)) continue; const item = revision(createUuidV7(), candidate, value.document); insertRecord(database, item.evidenceId, item.createdAt); insertRevision(database, item); insertCandidate(database, { documentId: record.id, sourceSection: candidate.sourceSection, lineNumber: candidate.lineNumber, contentDigest: candidate.contentDigest, evidenceRevisionId: item.id }); appendAuditEvent(database, createAuditEvent({ actor: "local-os-user", action: "evidence.library_candidate_created", outcome: "success", entityId: item.id, contentHash: item.contentDigest })); candidatesAdded += 1; } } return { documentsAdded, candidatesAdded, documents: stored }; }
async function persist(options: Options, source: { category: "project" | "experience" | "refresh"; identity: string; digest: string }, documents: MarkdownDocument[]): Promise<LibraryImportResult> { const prepared = prepare(documents); const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); database.exec("BEGIN IMMEDIATE;"); try { const existing = findImport(database, source.identity, source.digest); if (existing && source.category !== "refresh") throw new WorkspaceError("EVIDENCE_LIBRARY_DUPLICATE", "That source has already been added to the evidence library.", "Refresh the library or choose a different source folder."); const importId = existing?.id ?? createUuidV7(); if (!existing) insertImport(database, { id: importId, category: source.category, sourceIdentity: source.identity, sourceDigest: source.digest, createdAt: new Date().toISOString() }); const result = saveDocuments(database, prepared, importId); appendAuditEvent(database, createAuditEvent({ actor: "local-os-user", action: "evidence.library_imported", outcome: "success", entityId: importId, contentHash: source.digest })); database.exec("COMMIT;"); return result; } catch (error) { database.exec("ROLLBACK;"); throw error; } } finally { database.close(); } }
async function persistCopied(input: Options, source: { category: "project" | "experience"; identity: string; digest: string }, copied: CopiedLibraryContent): Promise<LibraryImportResult> { try { return await persist(input, source, copied.documents); } catch (error) { await copied.cleanup(); throw error; } }
export async function addProjectToEvidenceLibrary(input: Options & { sourceDirectory: string; name?: string }): Promise<LibraryImportResult> { const copied = await copyProjectMarkdown(input.sourceDirectory, input.name, input.workspaceRoot); return persistCopied(input, { category: "project", identity: `project:${hash(resolve(input.sourceDirectory))}`, digest: copied.sourceDigest }, copied); }
export async function addExperienceToEvidenceLibrary(input: Options & { name: string; markdown?: string; sourceFile?: string }): Promise<LibraryImportResult> { const copied = await copyExperienceMarkdown(input); return persistCopied(input, { category: "experience", identity: `experience:${input.name.trim().toLowerCase()}`, digest: copied.sourceDigest }, copied); }
export async function refreshEvidenceLibrary(input: Options = {}): Promise<LibraryImportResult> { const documents = await readManagedMarkdown(input.workspaceRoot); const digest = hash(documents.map((document) => `${document.libraryPath}:${document.contentDigest}`).sort().join("\n")); return persist(input, { category: "refresh", identity: `refresh:${digest}`, digest }, documents); }
export async function listEvidenceLibrary(options: Options = {}): Promise<EvidenceLibraryDocument[]> { const documents = await readManagedMarkdown(options.workspaceRoot).catch((error) => { if (error instanceof WorkspaceError && error.code === "EVIDENCE_LIBRARY_EMPTY") return []; throw error; }); if (!documents.length) return []; const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); return documents.flatMap((document) => { const record = findDocumentByPathAndDigest(database, document.libraryPath, document.contentDigest); return record ? [record] : []; }); } finally { database.close(); } }
export async function recordEvidenceLibraryFailure(options: Options = {}): Promise<void> { const paths = await resolveAppDataPaths(options.appDataRoot); const database = openDatabase(paths.databasePath); try { applyMigrations(database); appendAuditEvent(database, createAuditEvent({ actor: "local-os-user", action: "evidence.library_failed", outcome: "failure" })); } finally { database.close(); } }
