import type { DatabaseSync } from "node:sqlite";

export type ManagedArtifactKind = "backup" | "activity_history_export";
export type ManagedArtifactState = "active" | "trashed" | "expired" | "permanently_deleted";
export type ManagedArtifact = { id: string; artifactKind: ManagedArtifactKind; lifecycleState: ManagedArtifactState; storageLocation: string; contentDigest: string; byteSize: number; localRevision: number; createdAt: string; updatedAt: string; deletedAt?: string; expiresAt?: string };
type Row = Record<string, string | number | null>;
const fields = "id, artifact_kind, lifecycle_state, storage_location, content_digest, byte_size, local_revision, created_at, updated_at, deleted_at, expires_at";
function map(row: Row): ManagedArtifact { return { id: row.id as string, artifactKind: row.artifact_kind as ManagedArtifactKind, lifecycleState: row.lifecycle_state as ManagedArtifactState, storageLocation: row.storage_location as string, contentDigest: row.content_digest as string, byteSize: row.byte_size as number, localRevision: row.local_revision as number, createdAt: row.created_at as string, updatedAt: row.updated_at as string, deletedAt: row.deleted_at as string | undefined, expiresAt: row.expires_at as string | undefined }; }
export function insertManagedArtifact(db: DatabaseSync, item: ManagedArtifact): void { db.prepare(`INSERT INTO managed_artifacts (${fields}) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(item.id, item.artifactKind, item.lifecycleState, item.storageLocation, item.contentDigest, item.byteSize, item.localRevision, item.createdAt, item.updatedAt, item.deletedAt ?? null, item.expiresAt ?? null); }
export function getManagedArtifact(db: DatabaseSync, id: string): ManagedArtifact | undefined { const row = db.prepare(`SELECT ${fields} FROM managed_artifacts WHERE id = ?`).get(id) as Row | undefined; return row && map(row); }
export function listManagedArtifacts(db: DatabaseSync): ManagedArtifact[] { return (db.prepare(`SELECT ${fields} FROM managed_artifacts WHERE lifecycle_state != 'permanently_deleted' ORDER BY created_at DESC`).all() as Row[]).map(map); }
export function updateManagedArtifact(db: DatabaseSync, item: ManagedArtifact, expectedRevision: number): void { const result = db.prepare("UPDATE managed_artifacts SET lifecycle_state = ?, storage_location = ?, local_revision = ?, updated_at = ?, deleted_at = ?, expires_at = ? WHERE id = ? AND local_revision = ?").run(item.lifecycleState, item.storageLocation, item.localRevision, item.updatedAt, item.deletedAt ?? null, item.expiresAt ?? null, item.id, expectedRevision); if (result.changes !== 1) throw new Error("STALE_ARTIFACT"); }
export function markPermanentlyDeleted(db: DatabaseSync, id: string, expectedRevision: number, updatedAt: string): void { const result = db.prepare("UPDATE managed_artifacts SET lifecycle_state = 'permanently_deleted', local_revision = local_revision + 1, updated_at = ? WHERE id = ? AND local_revision = ? AND artifact_kind = 'backup'").run(updatedAt, id, expectedRevision); if (result.changes !== 1) throw new Error("STALE_ARTIFACT"); }
export type StorageCounts = { baseResumes: number; evidence: number; audits: number };
export function storageCounts(db: DatabaseSync): StorageCounts { const count = (table: string) => (db.prepare(`SELECT COUNT(*) AS count FROM ${table}`).get() as { count: number }).count; return { baseResumes: count("base_resumes"), evidence: count("evidence_records"), audits: count("audit_events") }; }
export type SafeAuditEvent = { id: string; occurredAt: string; actor: string; entityId?: string; action: string; outcome: string };
export function listSafeAuditEvents(db: DatabaseSync): SafeAuditEvent[] { return (db.prepare("SELECT id, occurred_at, actor, entity_id, action, outcome FROM audit_events ORDER BY occurred_at DESC").all() as Row[]).map((row) => ({ id: row.id as string, occurredAt: row.occurred_at as string, actor: row.actor as string, entityId: row.entity_id as string | undefined, action: row.action as string, outcome: row.outcome as string })); }
