import type { DatabaseSync } from "node:sqlite";

export type StoredFitAssessment = {
  id: string; jobListingId: string; candidateProfileRevisionId?: string; preferenceRevisionId: string;
  rulesetId: string; rulesetVersion: string; rulesetDigest: string; listingSnapshot: string;
  evidenceSnapshot: string; preferenceSnapshot: string; factorOutcomes: string; label: "Strong" | "Potential" | "Stretch";
  confidence: "high" | "medium" | "low"; freshness: string; calculatedAt: string; contentDigest: string;
};
type Row = Record<string, unknown>;
const map = (r: Row): StoredFitAssessment => ({ id: String(r.id), jobListingId: String(r.job_listing_id), candidateProfileRevisionId: r.candidate_profile_revision_id ? String(r.candidate_profile_revision_id) : undefined, preferenceRevisionId: String(r.preference_revision_id), rulesetId: String(r.ruleset_id), rulesetVersion: String(r.ruleset_version), rulesetDigest: String(r.ruleset_digest), listingSnapshot: String(r.listing_snapshot), evidenceSnapshot: String(r.evidence_snapshot), preferenceSnapshot: String(r.preference_snapshot), factorOutcomes: String(r.factor_outcomes), label: r.label as StoredFitAssessment["label"], confidence: r.confidence as StoredFitAssessment["confidence"], freshness: String(r.freshness), calculatedAt: String(r.calculated_at), contentDigest: String(r.content_digest) });
export function insertFitAssessment(db: DatabaseSync, value: StoredFitAssessment): void { db.prepare("INSERT INTO fit_assessments (id, job_listing_id, candidate_profile_revision_id, preference_revision_id, ruleset_id, ruleset_version, ruleset_digest, listing_snapshot, evidence_snapshot, preference_snapshot, factor_outcomes, label, confidence, freshness, calculated_at, content_digest) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run(value.id, value.jobListingId, value.candidateProfileRevisionId ?? null, value.preferenceRevisionId, value.rulesetId, value.rulesetVersion, value.rulesetDigest, value.listingSnapshot, value.evidenceSnapshot, value.preferenceSnapshot, value.factorOutcomes, value.label, value.confidence, value.freshness, value.calculatedAt, value.contentDigest); }
export function listFitAssessments(db: DatabaseSync, listingId: string, limit = 20): StoredFitAssessment[] { const bounded = Math.max(1, Math.min(100, Math.trunc(limit))); return (db.prepare("SELECT * FROM fit_assessments WHERE job_listing_id = ? ORDER BY calculated_at DESC LIMIT ?").all(listingId, bounded) as Row[]).map(map); }
export function latestFitAssessment(db: DatabaseSync, listingId: string): StoredFitAssessment | undefined { const row = db.prepare("SELECT * FROM fit_assessments WHERE job_listing_id = ? ORDER BY calculated_at DESC LIMIT 1").get(listingId) as Row | undefined; return row ? map(row) : undefined; }
