import type { DatabaseSync } from "node:sqlite";
import { WorkspaceError } from "@/domain/workspace/types";

export type StoredJobListing = { id: string; title: string; company: string; workStyle?: string; location?: string; duplicateKey: string; duplicateGroupId: string; firstSeenAt: string; lastObservedAt: string; contentDigest: string };
export type StoredSourceRecord = { id: string; jobListingId: string; sourceId: string; sourceConfigurationRevisionId: string; refreshRunId?: string; originalUrl: string; postedAt?: string; observedAt: string; contentDigest: string };
export type StoredDuplicateOverride = { id: string; jobListingId: string; previousGroupId: string; newGroupId: string; status: "applied" | "reversed"; createdAt: string; reversedAt?: string; contentDigest: string };

const iso = (value: unknown) => typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) && !Number.isNaN(Date.parse(value));
const uuid = (value: unknown) => typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const digest = (value: unknown) => typeof value === "string" && /^sha256:[0-9a-f]{64}$/i.test(value);
const validUrl = (value: unknown) => { try { const parsed = new URL(String(value)); return parsed.protocol === "https:" && !parsed.username && !parsed.password && parsed.toString().length <= 2048; } catch { return false; } };
const safe = (condition: boolean): void => { if (!condition) throw new WorkspaceError("JOB_LISTING_INVALID", "Stored Job Listing data is invalid.", "Check local workspace storage, then repair or re-import the affected listing."); };
const listing = (row: Record<string, unknown>): StoredJobListing => { safe(uuid(row.id) && typeof row.title === "string" && row.title.length >= 1 && row.title.length <= 300 && typeof row.company === "string" && row.company.length >= 1 && row.company.length <= 300 && (!row.work_style || String(row.work_style).length <= 120) && (!row.location || String(row.location).length <= 300) && typeof row.duplicate_key === "string" && row.duplicate_key.length <= 700 && uuid(row.duplicate_group_id) && iso(row.first_seen_at) && iso(row.last_observed_at) && digest(row.content_digest)); return { id: String(row.id), title: String(row.title), company: String(row.company), workStyle: row.work_style ? String(row.work_style) : undefined, location: row.location ? String(row.location) : undefined, duplicateKey: String(row.duplicate_key), duplicateGroupId: String(row.duplicate_group_id), firstSeenAt: String(row.first_seen_at), lastObservedAt: String(row.last_observed_at), contentDigest: String(row.content_digest) }; };
const sourceRecord = (row: Record<string, unknown>): StoredSourceRecord => { safe(uuid(row.id) && uuid(row.job_listing_id) && uuid(row.source_id) && uuid(row.source_configuration_revision_id) && (!row.refresh_run_id || uuid(row.refresh_run_id)) && validUrl(row.original_url) && (!row.posted_at || iso(row.posted_at)) && iso(row.observed_at) && digest(row.content_digest)); return { id: String(row.id), jobListingId: String(row.job_listing_id), sourceId: String(row.source_id), sourceConfigurationRevisionId: String(row.source_configuration_revision_id), refreshRunId: row.refresh_run_id ? String(row.refresh_run_id) : undefined, originalUrl: String(row.original_url), postedAt: row.posted_at ? String(row.posted_at) : undefined, observedAt: String(row.observed_at), contentDigest: String(row.content_digest) }; };
const override = (row: Record<string, unknown>): StoredDuplicateOverride => ({ id: String(row.id), jobListingId: String(row.job_listing_id), previousGroupId: String(row.previous_group_id), newGroupId: String(row.new_group_id), status: String(row.status) as StoredDuplicateOverride["status"], createdAt: String(row.created_at), reversedAt: row.reversed_at ? String(row.reversed_at) : undefined, contentDigest: String(row.content_digest) });

export function insertJobListing(database: DatabaseSync, value: StoredJobListing): void { database.prepare("INSERT INTO job_listings (id, title, company, work_style, location, duplicate_key, duplicate_group_id, first_seen_at, last_observed_at, content_digest) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run(value.id, value.title, value.company, value.workStyle ?? null, value.location ?? null, value.duplicateKey, value.duplicateGroupId, value.firstSeenAt, value.lastObservedAt, value.contentDigest); }
export function insertSourceRecord(database: DatabaseSync, value: StoredSourceRecord): void { database.prepare("INSERT INTO retained_job_source_records (id, job_listing_id, source_id, source_configuration_revision_id, refresh_run_id, original_url, posted_at, observed_at, content_digest) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(value.id, value.jobListingId, value.sourceId, value.sourceConfigurationRevisionId, value.refreshRunId ?? null, value.originalUrl, value.postedAt ?? null, value.observedAt, value.contentDigest); }
export function findListingByDuplicateKey(database: DatabaseSync, duplicateKey: string): StoredJobListing | undefined { const row = database.prepare("SELECT * FROM job_listings WHERE duplicate_key = ? ORDER BY first_seen_at LIMIT 1").get(duplicateKey) as Record<string, unknown> | undefined; return row ? listing(row) : undefined; }
export function listStoredJobListings(database: DatabaseSync): StoredJobListing[] { return (database.prepare("SELECT * FROM job_listings ORDER BY last_observed_at DESC").all() as Record<string, unknown>[]).map(listing); }
export function listSourceRecords(database: DatabaseSync, jobListingId: string): StoredSourceRecord[] { return (database.prepare("SELECT * FROM retained_job_source_records WHERE job_listing_id = ? ORDER BY observed_at DESC").all(jobListingId) as Record<string, unknown>[]).map(sourceRecord); }
export function getStoredJobListing(database: DatabaseSync, id: string): StoredJobListing | undefined { const row = database.prepare("SELECT * FROM job_listings WHERE id = ?").get(id) as Record<string, unknown> | undefined; return row ? listing(row) : undefined; }
export function moveListingGroup(database: DatabaseSync, id: string, groupId: string): void { database.prepare("UPDATE job_listings SET duplicate_group_id = ? WHERE id = ?").run(groupId, id); }
export function insertDuplicateOverride(database: DatabaseSync, value: StoredDuplicateOverride): void { database.prepare("INSERT INTO job_listing_duplicate_overrides (id, job_listing_id, previous_group_id, new_group_id, status, created_at, reversed_at, content_digest) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").run(value.id, value.jobListingId, value.previousGroupId, value.newGroupId, value.status, value.createdAt, value.reversedAt ?? null, value.contentDigest); }
export function getDuplicateOverride(database: DatabaseSync, id: string): StoredDuplicateOverride | undefined { const row = database.prepare("SELECT * FROM job_listing_duplicate_overrides WHERE id = ?").get(id) as Record<string, unknown> | undefined; return row ? override(row) : undefined; }
export function activeDuplicateOverride(database: DatabaseSync, jobListingId: string): StoredDuplicateOverride | undefined { const row = database.prepare("SELECT * FROM job_listing_duplicate_overrides WHERE job_listing_id = ? AND status = 'applied' ORDER BY created_at DESC LIMIT 1").get(jobListingId) as Record<string, unknown> | undefined; return row ? override(row) : undefined; }
export function reverseStoredDuplicateOverride(database: DatabaseSync, id: string, reversedAt: string): void { database.prepare("UPDATE job_listing_duplicate_overrides SET status = 'reversed', reversed_at = ? WHERE id = ? AND status = 'applied'").run(reversedAt, id); }
