"use client";

import { useActionState, useState } from "react";
import Link from "next/link";

import { currentBaseResumeAction, type WorkspaceActionState } from "@/app/actions";
import type { EvidenceRevision } from "@/persistence/evidence-repository";
import type { CurrentBaseResumeDraft, CurrentBaseResumeProposal, CurrentBaseResumeVersion } from "@/persistence/current-base-resume-repository";

const initial: WorkspaceActionState = { status: "idle", summary: "Choose a text-readable PDF to create a Current Base Resume." };
type Props = { sourceCount: number; draft?: CurrentBaseResumeDraft; proposals: CurrentBaseResumeProposal[]; versions: CurrentBaseResumeVersion[]; evidence: EvidenceRevision[]; error?: { summary: string; safeNextAction: string } };
const fields: Array<keyof CurrentBaseResumeDraft["content"]> = ["contact", "summary", "experience", "projects", "education", "skills", "other"];

function labelFor(field: string) { return field[0].toUpperCase() + field.slice(1); }
function evidenceLabel(evidence: EvidenceRevision) { return `${evidence.sourceDocument}, ${evidence.sourceSection}`; }

export function CurrentBaseResume({ sourceCount, draft, proposals, versions, evidence, error }: Props) {
  const [state, action, pending] = useActionState(currentBaseResumeAction, initial);
  const revisionKey = draft ? `${draft.id}-${draft.revisionNumber}` : "no-draft";
  const [previewState, setPreviewState] = useState({ revisionKey, content: draft?.content, hasUnsavedEdits: false });
  const message = error ? { status: "error" as const, ...error } : state;
  const previewMatchesDraft = previewState.revisionKey === revisionKey;
  const content = previewMatchesDraft ? previewState.content ?? draft?.content : draft?.content;
  const hasUnsavedEdits = previewMatchesDraft && previewState.hasUnsavedEdits;
  const evidenceByRevision = new Map(evidence.map((item) => [item.id, item]));

  return <section aria-labelledby="current-base-resume-heading" className="panel">
    <h3 id="current-base-resume-heading">Current Base Resume</h3>
    <p>Import a text-readable PDF. The original stays unchanged; this creates a private source copy and an editable structured draft.</p>
    <form action={action}><input type="hidden" name="currentResumeCommand" value="import" /><label htmlFor="current-resume-pdf">Current Base Resume PDF</label><input id="current-resume-pdf" name="currentResumePdf" type="file" accept="application/pdf,.pdf" required aria-invalid={message.status === "error"} aria-describedby={message.status === "error" ? "current-resume-error" : undefined} /><button type="submit" disabled={pending}>Import PDF</button></form>
    <p id={message.status === "error" ? "current-resume-error" : undefined} role="status" aria-live="polite" className={message.status === "error" ? "status status-error" : "status"}>{message.summary}</p>
    {"safeNextAction" in message && message.safeNextAction ? <p><strong>Safe next action:</strong> {message.safeNextAction}</p> : null}
    {sourceCount ? <p>{sourceCount} retained PDF source {sourceCount === 1 ? "is" : "are"} available.</p> : <p>No Current Base Resume PDF has been imported yet.</p>}
    {draft && content ? <>
      <nav className="resume-review-jumps" aria-label="Resume review sections"><a href="#resume-editor">Editor</a><a href="#resume-preview">Preview</a><a href="#resume-warnings">Warnings</a><a href="#resume-provenance">Provenance</a></nav>
      <section className="resume-review-summary" aria-labelledby="resume-review-summary-heading"><h4 id="resume-review-summary-heading">Review summary</h4><p><strong>{proposals.filter((proposal) => proposal.decision === "open").length} open warning{proposals.filter((proposal) => proposal.decision === "open").length === 1 ? "" : "s"}</strong> need review before an approved version can be created. Previewing does not approve or export anything.</p></section>
      <div className="resume-editor-preview">
        <form action={action} className="draft-editor" id="resume-editor"><input type="hidden" name="currentResumeCommand" value="save" /><input type="hidden" name="draftId" value={draft.id} /><h4>Editor</h4><p className="revision-status">Editing local draft revision {draft.revisionNumber}. {hasUnsavedEdits ? "Preview includes unsaved local edits; save before approving a version." : "Preview matches the saved local revision."}</p>{fields.map((field) => <label key={field} htmlFor={`draft-${field}`}>{labelFor(field)}<textarea id={`draft-${field}`} name={field} value={content[field].join("\n")} onChange={(event) => setPreviewState({ revisionKey, content: { ...content, [field]: event.currentTarget.value.split("\n") }, hasUnsavedEdits: true })} /></label>)}<button type="submit" disabled={pending}>Save draft revision</button></form>
        <aside id="resume-preview" className="resume-preview" aria-label="Resume preview" aria-labelledby="resume-preview-heading"><h4 id="resume-preview-heading">Preview</h4><p className="revision-status">Read-only local text preview of revision {draft.revisionNumber}{hasUnsavedEdits ? " with unsaved edits" : ""}.</p>{fields.map((field) => content[field].length ? <section key={field}><h5>{labelFor(field)}</h5>{content[field].map((line, index) => <p key={`${field}-${index}`}>{line}</p>)}</section> : null)}<p className="preview-boundary">No scripts, remote assets, or cloud processing are used. If this preview is unavailable, your draft remains local and available as a safe text-only review.</p></aside>
      </div>
      <section id="resume-warnings" aria-labelledby="proposal-heading"><h4 id="proposal-heading">Warnings and proposed changes</h4>{proposals.length ? <ul>{proposals.map((proposal) => { const support = evidenceByRevision.get(proposal.evidenceRevisionId); return <li key={proposal.id}><p>{proposal.proposedText}</p><p>Evidence support: {support ? <>{evidenceLabel(support)}. {support.origin === "extracted" ? "Extracted" : "User-entered"}. <Link href={`/evidence#evidence-${support.id}`}>Review this evidence</Link></> : <>The evidence reference is unavailable. <Link href="/evidence#evidence-heading">Open Evidence Review</Link></>}</p>{proposal.decision === "open" ? <form action={action}><input type="hidden" name="currentResumeCommand" value="resolve" /><input type="hidden" name="proposalId" value={proposal.id} /><input type="hidden" name="expectedDecisionRevisionId" value={proposal.decisionRevisionId} /><label htmlFor={`proposal-${proposal.id}`}>Edited wording (optional)</label><textarea id={`proposal-${proposal.id}`} name="proposalText" /><button className="affirmative-action" name="decision" value="approved" type="submit">Approve</button> <button className="neutral-action" name="decision" value="edited" type="submit">Save edited</button> <button className="danger-action" name="decision" value="rejected" type="submit">Reject</button></form> : <p>Resolved: {proposal.decision}</p>}</li>; })}</ul> : <p>No proposed changes have been generated.</p>}</section>
      <section id="resume-provenance" aria-labelledby="resume-provenance-heading"><h4 id="resume-provenance-heading">Evidence and skills</h4><p>Each evidence support reference stays visible at its review decision. Only approved evidence can support a future material.</p><div className="evidence-chip-list">{proposals.length ? proposals.map((proposal) => { const support = evidenceByRevision.get(proposal.evidenceRevisionId); return <Link className="evidence-chip" href={support ? `/evidence#evidence-${support.id}` : "/evidence#evidence-heading"} key={proposal.id}>Evidence: {support ? `${support.sourceDocument} · ${support.reviewState === "approved" ? "Approved" : support.reviewState === "unreviewed" ? "Ready for review" : support.reviewState === "rejected" ? "Not using" : "Removed"}` : "Open Evidence Review"}</Link>; }) : <span className="evidence-chip">No evidence proposals yet</span>}{content.skills.map((skill) => <span className="evidence-chip" key={skill}>Skill · {skill}</span>)}</div></section>
      <form action={action}><input type="hidden" name="currentResumeCommand" value="propose" /><input type="hidden" name="draftId" value={draft.id} /><button type="submit" disabled={pending}>Update Base Resume from approved evidence</button></form>
      <form action={action} key={revisionKey}><input type="hidden" name="currentResumeCommand" value="approve-version" /><input type="hidden" name="draftId" value={draft.id} /><label><input type="checkbox" name="explicitApproval" value="yes" required disabled={hasUnsavedEdits} /> I approve this Current Base Resume version.</label>{hasUnsavedEdits ? <p className="revision-status">Save the displayed edits before approving this revision.</p> : null}<button type="submit" disabled={pending || hasUnsavedEdits}>Approve Current Base Resume version</button></form>
    </> : null}
    <section aria-labelledby="versions-heading"><h4 id="versions-heading">Retained Current Base Resume versions</h4>{versions.length ? <ul>{versions.map((version) => <li key={version.id}>{version.sourceFilename}, draft revision {version.draftRevisionNumber}, approved {new Date(version.approvedAt).toLocaleString()}. Evidence support: {version.evidenceRevisionIds.length ? version.evidenceRevisionIds.map((id, index) => { const support = evidenceByRevision.get(id); return support ? <span key={id}>{index ? "; " : ""}<Link href={`/evidence#evidence-${support.id}`}>{evidenceLabel(support)}</Link></span> : <span key={id}>{index ? "; " : ""}a retained evidence reference that is no longer available</span>; }) : "none"}. {version.evidenceRevisionIds.length ? <details><summary>Technical support details</summary><p>Retained evidence revision identifiers: {version.evidenceRevisionIds.map((id) => <code key={id}> {id}</code>)}</p></details> : null}</li>)}</ul> : <p>No Current Base Resume version has been approved yet.</p>}</section>
  </section>;
}
