"use client";

import { useActionState, useState } from "react";
import { evidenceLibraryAction, type WorkspaceActionState } from "@/app/actions";
import type { EvidenceLibraryDocument } from "@/persistence/evidence-library-repository";
import type { StoredDocumenterProposal } from "@/persistence/evidence-documenter-repository";

const initial: WorkspaceActionState = { status: "idle", summary: "Add reviewed Markdown evidence when you choose. The library is never watched in the background." };
export function EvidenceLibrary({ documents, documenterProposals, error, documenterError }: { documents: EvidenceLibraryDocument[]; documenterProposals: StoredDocumenterProposal[]; error?: { summary: string; safeNextAction: string }; documenterError?: { summary: string; safeNextAction: string } }) {
  const [state, action, pending] = useActionState(evidenceLibraryAction, initial); const isError = state.status === "error";
  const [cancelled, setCancelled] = useState(false);
  return <section aria-labelledby="evidence-library-heading" className="panel"><h2 id="evidence-library-heading">Resume &amp; Evidence Library</h2><p>Your visible <code>resume-evidence</code> folder stores reviewed Markdown evidence. Adding or refreshing is always explicit; source folders are copied and never changed.</p>
    <div className="library-actions">
      <form action={action}><input type="hidden" name="libraryCommand" value="add-project" /><h3>Add Project</h3><label htmlFor="project-folder">Project folder</label><input id="project-folder" name="sourceDirectory" required aria-invalid={isError} aria-describedby={isError ? "library-status" : undefined} placeholder="Select or paste a local project folder" /><label htmlFor="project-name">Library project name (optional)</label><input id="project-name" name="projectName" aria-invalid={isError} aria-describedby={isError ? "library-status" : undefined} /><button type="submit" disabled={pending}>Add Project</button></form>
      <form action={action} onSubmit={() => setCancelled(false)}><input type="hidden" name="libraryCommand" value="document-for-resume" /><h3>Document for Resume (optional)</h3><p>Only readable Markdown in the selected folder is sent to your configured local LM Studio model. The source folder is never changed, and results require individual review.</p><label htmlFor="document-project-folder">Project/document folder</label><input id="document-project-folder" name="sourceDirectory" required aria-invalid={isError} aria-describedby={isError ? "library-status" : undefined} placeholder="Paste a local project folder" /><label><input type="checkbox" name="localModelDisclosure" value="yes" required /> I confirm this selected folder&apos;s Markdown may be processed by my local LM Studio model.</label><button type="submit" disabled={pending}>Document for Resume</button> <button type="reset" disabled={pending} onClick={() => setCancelled(true)}>Cancel</button></form>
      <form action={action}><input type="hidden" name="libraryCommand" value="add-experience" /><h3>Add Experience</h3><label htmlFor="experience-name">Experience name</label><input id="experience-name" name="experienceName" required aria-invalid={isError} aria-describedby={isError ? "library-status" : undefined} /><label htmlFor="experience-markdown">Experience Markdown</label><textarea id="experience-markdown" name="markdown" aria-invalid={isError} aria-describedby={isError ? "library-status" : undefined} /><label htmlFor="experience-file">Or select a Markdown file</label><input id="experience-file" name="experienceFile" type="file" accept=".md,text/markdown" aria-invalid={isError} aria-describedby={isError ? "library-status" : undefined} /><button type="submit" disabled={pending}>Add Experience</button></form>
      <form action={action}><input type="hidden" name="libraryCommand" value="refresh" /><h3>Refresh Library</h3><p>Re-read the managed Markdown folder and add only new evidence candidates.</p><button type="submit" disabled={pending}>Refresh Library</button></form>
    </div>
    <p id="library-status" role="status" aria-live="polite" className={isError ? "status status-error" : "status"}>{cancelled ? "Documentation cancelled before it started." : state.summary}{!cancelled && state.safeNextAction ? <> <strong>Safe next action:</strong> {state.safeNextAction}</> : null}</p>
    {documenterError ? <p className="status status-error" role="status">{documenterError.summary} <strong>Safe next action:</strong> {documenterError.safeNextAction}</p> : null}
    {documenterProposals.length ? <section aria-labelledby="documenter-proposals-heading"><h3 id="documenter-proposals-heading">Document for Resume proposals</h3><p>These are untrusted suggestions. Accepted or edited items become unreviewed evidence and cannot support a resume until separately approved in Evidence Review.</p><ul>{documenterProposals.map((proposal) => <li key={proposal.id}><p>{proposal.factualText}</p><p>Sources: {proposal.sourcePaths.join(", ")}. Unknowns: {proposal.unknowns.join("; ")}.</p><p>State: {proposal.state}.</p>{proposal.state === "proposed" ? <><form action={action}><input type="hidden" name="libraryCommand" value="resolve-document-proposal" /><input type="hidden" name="proposalId" value={proposal.id} /><input type="hidden" name="expectedRevisionId" value={proposal.revisionId} /><input type="hidden" name="decision" value="accepted" /><button type="submit" disabled={pending}>Accept as unreviewed evidence</button></form><form action={action}><input type="hidden" name="libraryCommand" value="resolve-document-proposal" /><input type="hidden" name="proposalId" value={proposal.id} /><input type="hidden" name="expectedRevisionId" value={proposal.revisionId} /><label htmlFor={`proposal-edit-${proposal.id}`}>Edit factual text</label><textarea id={`proposal-edit-${proposal.id}`} name="factualText" defaultValue={proposal.factualText} required /><button type="submit" name="decision" value="edited" disabled={pending}>Save edited as unreviewed evidence</button><button type="submit" formNoValidate name="decision" value="rejected" disabled={pending}>Reject proposal</button></form></> : null}</li>)}</ul></section> : null}
    {error ? <p className="status status-error" role="status">{error.summary} <strong>Safe next action:</strong> {error.safeNextAction}</p> : documents.length === 0 ? <p>No project or experience documents have been added yet.</p> : <section aria-labelledby="library-inventory-heading"><h3 id="library-inventory-heading">Library inventory</h3><ul>{documents.map((document) => <li key={document.id}><strong>{document.category === "project" ? "Project" : "Experience"}</strong> — {document.libraryPath.split("/").at(-1)}; added {new Date(document.importedAt).toLocaleString()}</li>)}</ul></section>}
  </section>;
}
