"use client";
import { useActionState } from "react";
import { evidenceAction, type WorkspaceActionState } from "@/app/actions";
import type { EvidenceRevision } from "@/persistence/evidence-repository";
type Props = { evidence: EvidenceRevision[]; baseResumeIds: string[] };
const initial: WorkspaceActionState = { status: "idle", summary: "Review each evidence item before it can support future claims." };
export function EvidenceReview({ evidence, baseResumeIds }: Props) {
  const [state, action, pending] = useActionState(evidenceAction, initial); const error = state.status === "error";
  return <section aria-labelledby="evidence-heading" className="panel"><h3 id="evidence-heading">Evidence review</h3><p>Only current approved evidence is claim eligible.</p>
    {baseResumeIds.length ? <form action={action}><input type="hidden" name="evidenceCommand" value="extract" /><label htmlFor="base-resume-id">Base Resume to extract</label><select id="base-resume-id" name="baseResumeId">{baseResumeIds.map((id) => <option key={id} value={id}>{id}</option>)}</select><button type="submit" disabled={pending}>Extract facts from Base Resume</button></form> : <p>Import a Base Resume before extracting facts.</p>}
    <form action={action}><input type="hidden" name="evidenceCommand" value="add" /><label htmlFor="evidence-text">Factual text</label><textarea id="evidence-text" name="factualText" aria-invalid={error} aria-describedby={error ? "evidence-error" : undefined} /><label htmlFor="evidence-source">Source document</label><input id="evidence-source" name="sourceDocument" aria-invalid={error} aria-describedby={error ? "evidence-error" : undefined} /><label htmlFor="evidence-section">Source section</label><input id="evidence-section" name="sourceSection" aria-invalid={error} aria-describedby={error ? "evidence-error" : undefined} /><button type="submit" disabled={pending}>Add evidence</button></form>
    <p id={error ? "evidence-error" : undefined} role="status" aria-live="polite" className={error ? "status status-error" : "status"}>{state.summary}</p>
    {evidence.length === 0 ? <p>No evidence has been added or extracted yet.</p> : <ul>{evidence.map((item) => <li key={item.id}><p><strong>{item.origin === "extracted" ? "Extracted" : "User-entered"}</strong> — {item.reviewState}, revision {item.revisionNumber}</p><p>{item.factualText}</p><p>Source: {item.sourceDocument}, {item.sourceSection}</p>{item.reviewState === "removed" ? <p>Removed evidence cannot be changed.</p> : <form action={action}><input type="hidden" name="evidenceId" value={item.evidenceId} /><input type="hidden" name="expectedRevisionId" value={item.id} /><label htmlFor={`evidence-edit-${item.id}`}>Edit factual text</label><input id={`evidence-edit-${item.id}`} name="factualText" defaultValue={item.factualText} aria-invalid={error} aria-describedby={error ? "evidence-error" : undefined} /><button name="evidenceCommand" value="edit" disabled={pending}>Edit</button><button name="evidenceCommand" value="approve" disabled={pending}>Approve</button><button name="evidenceCommand" value="reject" disabled={pending}>Reject</button><button name="evidenceCommand" value="remove" disabled={pending}>Remove</button></form>}</li>)}</ul>}
  </section>;
}
