"use client";

import { useActionState, useEffect, useRef, useState, type ChangeEvent, type FormEvent } from "react";
import { evidenceAction, evidenceLibraryAction, type WorkspaceActionState } from "@/app/actions";
import type { ExperienceProjectCollection } from "@/domain/evidence/evidence-library";

const initial: WorkspaceActionState = { status: "idle", summary: "Choose a real folder and document it with your configured local AI." };
const reviewLabel = { unreviewed: "Ready for review", approved: "Approved", rejected: "Not using", removed: "Removed" } as const;
const categoryLabel = { project: "Project", experience: "Experience" } as const;
const allowedExtensions = new Set([".md", ".txt", ".js", ".mjs", ".cjs", ".jsx", ".ts", ".tsx", ".py", ".go", ".rs", ".java", ".kt", ".c", ".h", ".cpp", ".hpp", ".cs", ".rb", ".php", ".sql", ".sh", ".ps1", ".json", ".toml", ".ini", ".cfg", ".xml", ".yaml", ".yml"]);
const excludedDirectories = new Set(["node_modules", ".git", ".hg", ".svn", "dist", "build", "out", ".next", "coverage", ".nyc_output", ".cache", "cache", "tmp", "temp", "vendor", "target", "__pycache__", ".venv", "venv", "generated"]);
const generatedFile = (name: string) => /(?:^|[._-])(?:generated|autogen|auto-generated)(?:[._-]|$)|\.min\.(?:js|css)$/i.test(name);
type SelectedSource = { files: File[]; manifest: { root: string; files: Array<{ path: string; name: string; size: number }> }; rootName: string };
function eligibleFiles(event: ChangeEvent<HTMLInputElement>): SelectedSource | undefined {
  const entries = Array.from(event.currentTarget.files ?? []); const rootName = entries[0]?.webkitRelativePath.split("/")[0] || "selected folder"; const seen = new Set<string>(); const files: File[] = []; let estimatedSnapshotBytes = 0;
  const manifestFiles: SelectedSource["manifest"]["files"] = [];
  for (const file of entries) { const parts = (file.webkitRelativePath || file.name).split("/"); const path = parts.slice(1).join("/"); const extension = `.${file.name.split(".").at(-1)?.toLowerCase() ?? ""}`; const estimate = file.size + path.length + rootName.length + 120; if (parts[0] !== rootName || !path || path.includes("\\") || path.split("/").some((part) => !part || part === "." || part === ".." || excludedDirectories.has(part.toLowerCase())) || seen.has(path) || generatedFile(file.name) || !allowedExtensions.has(extension) || !file.size || file.size > 8_000 || files.length >= 60 || estimatedSnapshotBytes + estimate > 12_000) continue; seen.add(path); estimatedSnapshotBytes += estimate; files.push(file); manifestFiles.push({ path: `${rootName}/${path}`, name: file.name, size: file.size }); }
  return files.length ? { files, manifest: { root: rootName, files: manifestFiles }, rootName } : undefined;
}

export function EvidenceLibrary({ collection, error }: { collection: ExperienceProjectCollection[]; error?: { summary: string; safeNextAction: string } }) {
  const [category, setCategory] = useState<"project" | "experience">("project");
  const [open, setOpen] = useState(false); const [expanded, setExpanded] = useState<string>();
  const [state, action, pending] = useActionState(evidenceLibraryAction, initial);
  const [reviewState, reviewAction, reviewing] = useActionState(evidenceAction, initial);
  const [selectedSource, setSelectedSource] = useState<SelectedSource>(); const [selectionMessage, setSelectionMessage] = useState("Choose a folder to inspect eligible source files."); const [pickerSupported, setPickerSupported] = useState(true); const chooserRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (state.status === "idle") return; let active = true; queueMicrotask(() => { if (!active) return; setSelectedSource(undefined); setSelectionMessage("Choose a folder to inspect eligible source files."); if (chooserRef.current) chooserRef.current.value = ""; }); return () => { active = false; }; }, [state.status]);
  const submitDocumentation = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedSource) return; const form = new FormData(event.currentTarget); form.delete("sourceFile"); form.set("sourceManifest", JSON.stringify(selectedSource.manifest)); for (const file of selectedSource.files) form.append("sourceFile", file); action(form); };
  const selected = collection.filter((item) => item.category === category); const label = categoryLabel[category];
  return <section className="experience-projects-collection" aria-labelledby="experience-projects-heading">
    <div className="experience-projects-intro"><p className="eyebrow">Your work</p><h2 id="experience-projects-heading">Projects and experiences</h2><p>Give your local AI one real working folder. It reads only safe, bounded material and returns proposed review documents; it never changes the source.</p></div>
    <div className="experience-project-tabs" role="tablist" aria-label="Work type"><button id="projects-tab" type="button" role="tab" aria-selected={category === "project"} aria-controls="work-type-panel" onClick={() => { setCategory("project"); setOpen(false); }}>Projects</button><button id="experiences-tab" type="button" role="tab" aria-selected={category === "experience"} aria-controls="work-type-panel" onClick={() => { setCategory("experience"); setOpen(false); }}>Experiences</button></div>
    <section id="work-type-panel" role="tabpanel" aria-labelledby={category === "project" ? "projects-tab" : "experiences-tab"}>
      <div className="experience-project-actions"><button type="button" className="affirmative-action" onClick={() => setOpen((value) => !value)}>{category === "project" ? "Document project folder" : "Document experience folder"}</button><p>One consented local-LLM documentation run, then individual evidence review.</p></div>
      {open ? <section className="documentation-handoff panel" aria-labelledby="documentation-handoff-heading"><h3 id="documentation-handoff-heading">Document this {label.toLowerCase()}</h3><p>The selected folder may contain source code, tests, docs, manifests, configuration, assets, and generated material. The agent reads an allowlisted snapshot only, writes no source files, and keeps unsupported content as unknown.</p><p>It creates exactly <code>project-overview.md</code>, <code>resume-evidence.md</code>, and <code>resume-bullet-candidates.md</code>. Results are proposed and unreviewed until you approve evidence items individually.</p>{pickerSupported ? <form onSubmit={submitDocumentation} className="generated-document-import"><input type="hidden" name="libraryCommand" value="document-source-folder" /><input type="hidden" name="category" value={category} /><label htmlFor="documented-item-name">{label} name</label><input id="documented-item-name" name="itemName" required aria-invalid={state.status === "error"} aria-describedby="documentation-status" /><label htmlFor="source-folder">Choose {label.toLowerCase()} folder</label><input id="source-folder" type="file" multiple required ref={(node) => { chooserRef.current = node; node?.setAttribute("webkitdirectory", ""); }} onClick={(event) => { if (!("webkitdirectory" in HTMLInputElement.prototype)) { event.preventDefault(); setPickerSupported(false); } }} onChange={(event) => { const source = eligibleFiles(event); setSelectedSource(source); setSelectionMessage(source ? `${source.rootName}: ${source.files.length} eligible file${source.files.length === 1 ? "" : "s"} selected.` : "No eligible text files were found. Choose a smaller folder with supported source files."); }} aria-invalid={state.status === "error"} aria-describedby="folder-selection-status documentation-status" /><p id="folder-selection-status" role="status" aria-live="polite" aria-atomic="true">{selectionMessage}</p><label><input type="checkbox" name="localModelDisclosure" value="yes" required /> I confirm this folder may be inspected by my configured local AI.</label><button type="submit" disabled={pending || !selectedSource}>Document folder</button></form> : <p className="status status-error">Folder selection requires a supported local browser. Update your browser, then choose the folder again.</p>}</section> : null}
      <p id="documentation-status" role="status" aria-live="polite" aria-atomic="true" className={state.status === "error" ? "status status-error" : "status"}>{state.summary}{state.safeNextAction ? <> <strong>Safe next action:</strong> {state.safeNextAction}</> : null}</p>{error ? <p className="status status-error" role="status">{error.summary} <strong>Safe next action:</strong> {error.safeNextAction}</p> : null}
      {selected.length === 0 ? <div className="collection-empty"><h3>No documented {label.toLowerCase()}s yet</h3><p>Start one local documentation run above.</p></div> : <ul className="experience-project-list">{selected.map((item) => { const key = `${item.category}-${item.name}`; const detailsOpen = expanded === key; return <li key={key} className="experience-project-row"><div><h3>{item.name}</h3><p>{item.summary}</p><p className="collection-meta">3 proposed review documents · {item.evidence.length} evidence item{item.evidence.length === 1 ? "" : "s"} · {item.evidence.some((e) => e.reviewState === "unreviewed") ? "Ready for review" : "Review complete"}</p></div><button type="button" className="neutral-action" aria-expanded={detailsOpen} aria-controls={`${key}-details`} onClick={() => setExpanded(detailsOpen ? undefined : key)}>View details</button>{detailsOpen ? <div id={`${key}-details`} className="experience-project-details"><p>Review documents: {item.artifactNames.join(", ")}.</p>{item.evidence.length ? <ul>{item.evidence.map((evidence) => <li key={evidence.reviewHandle}><p>{evidence.factualText}</p><p>{reviewLabel[evidence.reviewState]}</p>{evidence.reviewState === "unreviewed" ? <form action={reviewAction}><input type="hidden" name="reviewHandle" value={evidence.reviewHandle} /><button className="affirmative-action" name="evidenceCommand" value="approve" type="submit" disabled={reviewing}>Approve</button><button className="danger-action" name="evidenceCommand" value="reject" type="submit" disabled={reviewing}>Reject</button></form> : null}</li>)}</ul> : <p>No supported evidence items were returned.</p>}<p role="status" aria-live="polite" aria-atomic="true" className={reviewState.status === "error" ? "status status-error" : "status"}>{reviewState.summary}</p></div> : null}</li>; })}</ul>}
    </section>
  </section>;
}
