import { EvidenceLibrary } from "@/app/evidence-library";
import { EvidenceReview } from "@/app/evidence-review";
import { listStoredBaseResumes } from "@/domain/base-resume/list-base-resumes";
import { listStoredEvidence } from "@/domain/evidence/list-stored-evidence";
import { listEvidenceLibrary } from "@/domain/evidence/evidence-library";
import { listDocumenterProposals } from "@/domain/evidence/evidence-documenter";

const safeError = (error: unknown, fallback: string) => error instanceof Error && "summary" in error && "safeNextAction" in error ? { summary: String(error.summary), safeNextAction: String(error.safeNextAction) } : { summary: fallback, safeNextAction: "Check local workspace storage, then refresh the page." };
export async function EvidenceLibraryWorkspace() {
  const [base, evidence, library, proposals] = await Promise.all([listStoredBaseResumes().catch((error) => ({ resumes: [], error: safeError(error, "Base Resume history is unavailable.") })), listStoredEvidence().catch((error) => ({ evidence: [], error: safeError(error, "Evidence Review is unavailable.") })), listEvidenceLibrary().then((documents) => ({ documents, error: undefined })).catch((error) => ({ documents: [], error: safeError(error, "Evidence Library is unavailable.") })), listDocumenterProposals().then((items) => ({ items, error: undefined })).catch((error) => ({ items: [], error: safeError(error, "Document for Resume proposals are unavailable.") }))]);
  return <div className="workspace-shell evidence-workspace"><header className="workspace-header"><p className="eyebrow">Evidence Library</p><h1>Organize the proof behind your resume</h1><p>Add Markdown evidence only when you choose, then review each item before it can support future materials.</p></header><section aria-labelledby="evidence-lifecycle-heading" className="panel"><h2 id="evidence-lifecycle-heading">Evidence lifecycle</h2><dl className="evidence-lifecycle"><div><dt>Ready for review</dt><dd>New evidence needs your decision.</dd></div><div><dt>Approved</dt><dd>Eligible to support future materials.</dd></div><div><dt>Not using</dt><dd>Rejected evidence stays in history but is not used.</dd></div><div><dt>Removed</dt><dd>No longer usable as evidence.</dd></div></dl><p>Only approved evidence can support future materials.</p></section>{base.error ? <p className="status status-error" role="status">{base.error.summary} <strong>Safe next action:</strong> {base.error.safeNextAction}</p> : null}<section aria-labelledby="managed-library-heading"><h2 id="managed-library-heading">Managed evidence library</h2><p>Project and experience folders are inspected only through an explicit action. Markdown is copied locally; the selected source remains unchanged.</p><EvidenceLibrary documents={library.documents} documenterProposals={proposals.items} error={library.error} documenterError={proposals.error} /></section>{evidence.error ? <p className="status status-error" role="status">{evidence.error.summary} <strong>Safe next action:</strong> {evidence.error.safeNextAction}</p> : <EvidenceReview evidence={evidence.evidence} baseResumes={base.resumes.map((resume) => ({ id: resume.id, filename: resume.primaryFilename }))} />}</div>;
}
