"use client";

import { useActionState, useEffect, useRef, useState } from "react";

import { careersPageUrlAction, sourceConfigurationAction, type WorkspaceActionState } from "@/app/actions";
import type { SourceAccessPath, SourceConfiguration, SourceConfigurationsView, SourceConfigurationValues, SourceType } from "@/domain/discovery/source-configurations";

const initial: WorkspaceActionState = { status: "idle", summary: "Configure local source rules. Saving never retrieves jobs or visits a source." };
const careersPageInitial: WorkspaceActionState = { status: "idle", summary: "Paste an HTTPS careers-page URL to save a local manual-browser handoff." };
const empty: SourceConfigurationValues = { name: "", sourceType: "company-careers", url: "", accessPath: "manual-browser-handoff", policyRevision: "", policyReviewedOn: new Date().toISOString().slice(0, 10), policyApproved: false, requestBudget: 0, rateLimitPerMinute: 0, retentionRule: "No integration-fetched content; locally imported listings follow local lifecycle.", enabled: false, failureGuidance: "Stop and use the normal site page or manually import a selected listing." };
const types: Array<{ value: SourceType; label: string }> = [{ value: "company-careers", label: "Company careers page" }, { value: "job-platform", label: "Job platform" }, { value: "public-employment-service", label: "Public employment service" }];
const accessPaths: Array<{ value: SourceAccessPath; label: string }> = [{ value: "manual-browser-handoff", label: "Manual browser handoff" }, { value: "official-api", label: "Official API" }, { value: "published-feed", label: "Published feed" }, { value: "policy-reviewed-html", label: "Policy-reviewed HTML" }];

export function PermittedSources({ view, error }: { view: SourceConfigurationsView; error?: { summary: string; safeNextAction: string } }) {
  const [selected, setSelected] = useState<SourceConfiguration | undefined>(); const [values, setValues] = useState<SourceConfigurationValues>(empty); const [state, action, pending] = useActionState(sourceConfigurationAction, initial); const [careersPageState, careersPageAction, careersPagePending] = useActionState(careersPageUrlAction, careersPageInitial); const careersPageForm = useRef<HTMLFormElement>(null);
  const isError = state.status === "error" || Boolean(error); const describedBy = isError ? "permitted-sources-status" : undefined; const update = <K extends keyof SourceConfigurationValues>(key: K, value: SourceConfigurationValues[K]) => setValues((current) => ({ ...current, [key]: value }));
  const select = (source?: SourceConfiguration) => { setSelected(source); setValues(source?.values ?? empty); };
  useEffect(() => { if (careersPageState.status === "success") careersPageForm.current?.reset(); }, [careersPageState.status]); useEffect(() => { if (state.status === "success") queueMicrotask(() => select()); }, [state.status]);
  const manual = values.accessPath === "manual-browser-handoff"; const sourceNames = view.configurations.map((source) => source.values.name).join(", "); const allManual = view.configurations.length > 0 && view.configurations.every((source) => source.values.accessPath === "manual-browser-handoff");
  return <section id="permitted-sources" aria-labelledby="permitted-sources-heading" className="panel"><h2 id="permitted-sources-heading">Permitted Sources</h2><p>{sourceNames || "No sources are configured."} {allManual ? "All saved sources are manual-browser sources. No source is enabled for automatic retrieval." : "Saved source status is shown below; retrieval remains unavailable until a future approved source integration is added."}</p>
    <section aria-labelledby="careers-page-url-heading"><h3 id="careers-page-url-heading">Save a careers page URL</h3><p>This saves a local manual-browser handoff only. The page will not be opened or scanned.</p>
      <form ref={careersPageForm} action={careersPageAction}><label htmlFor="careers-page-url">Careers-page URL</label><input id="careers-page-url" name="careersPageUrl" type="url" inputMode="url" maxLength={2048} placeholder="https://example.com/careers" aria-invalid={careersPageState.status === "error"} aria-describedby="careers-page-url-status" required /><button type="submit" disabled={careersPagePending}>Save careers page URL</button></form>
      <p id="careers-page-url-status" role="status" aria-live="polite" className={careersPageState.status === "error" ? "status status-error" : "status"}>{careersPageState.summary}{careersPageState.safeNextAction ? <> <strong>Safe next action:</strong> {careersPageState.safeNextAction}</> : null}</p>
    </section>
    <div className="source-list"><h3>Saved sources</h3><ul>{view.configurations.map((source) => <li key={source.sourceId}><button type="button" onClick={() => select(source)}>{source.values.name}: {source.values.url}</button> — {source.values.accessPath === "manual-browser-handoff" ? "Manual only" : source.values.enabled ? "Enabled for future retrieval" : "Disabled"}</li>)}</ul><button type="button" onClick={() => select()}>Add a careers page or source</button></div>
    <form action={action}><input type="hidden" name="sourceId" value={selected?.sourceId ?? ""} /><input type="hidden" name="expectedRevisionId" value={selected?.revisionId ?? ""} />
      <label htmlFor="source-name">Source name</label><input id="source-name" name="name" value={values.name} onChange={(event) => update("name", event.target.value)} aria-invalid={isError} aria-describedby={describedBy} required />
      <label htmlFor="source-type">Source type</label><select id="source-type" name="sourceType" value={values.sourceType} onChange={(event) => update("sourceType", event.target.value as SourceType)} aria-invalid={isError} aria-describedby={describedBy}>{types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select>
      <label htmlFor="source-url">Source URL</label><input id="source-url" type="url" name="url" value={values.url} onChange={(event) => update("url", event.target.value)} aria-invalid={isError} aria-describedby={describedBy} required />
      <label htmlFor="access-path">Access path</label><select id="access-path" name="accessPath" value={values.accessPath} onChange={(event) => { const accessPath = event.target.value as SourceAccessPath; setValues((current) => ({ ...current, accessPath, requestBudget: accessPath === "manual-browser-handoff" ? 0 : Math.max(1, current.requestBudget), rateLimitPerMinute: accessPath === "manual-browser-handoff" ? 0 : Math.max(1, current.rateLimitPerMinute), enabled: accessPath === "manual-browser-handoff" ? false : current.enabled })); }} aria-invalid={isError} aria-describedby={describedBy}>{accessPaths.map((path) => <option key={path.value} value={path.value}>{path.label}</option>)}</select>
      <label htmlFor="policy-date">Policy review date</label><input id="policy-date" type="date" name="policyReviewedOn" value={values.policyReviewedOn} onChange={(event) => update("policyReviewedOn", event.target.value)} aria-invalid={isError} aria-describedby={describedBy} required />
      <label htmlFor="policy-revision">Policy revision</label><textarea id="policy-revision" name="policyRevision" value={values.policyRevision} onChange={(event) => update("policyRevision", event.target.value)} aria-invalid={isError} aria-describedby={describedBy} required />
      <label htmlFor="request-budget">Request budget</label><input id="request-budget" type="number" name="requestBudget" min="0" max="1000" value={values.requestBudget} readOnly={manual} onChange={(event) => update("requestBudget", Number(event.target.value))} aria-invalid={isError} aria-describedby={describedBy} />
      <label htmlFor="rate-limit">Rate limit per minute</label><input id="rate-limit" type="number" name="rateLimitPerMinute" min="0" max="120" value={values.rateLimitPerMinute} readOnly={manual} onChange={(event) => update("rateLimitPerMinute", Number(event.target.value))} aria-invalid={isError} aria-describedby={describedBy} />
      <label htmlFor="retention-rule">Retention rule</label><textarea id="retention-rule" name="retentionRule" value={values.retentionRule} onChange={(event) => update("retentionRule", event.target.value)} aria-invalid={isError} aria-describedby={describedBy} required />
      <label htmlFor="failure-guidance">Failure guidance</label><textarea id="failure-guidance" name="failureGuidance" value={values.failureGuidance} onChange={(event) => update("failureGuidance", event.target.value)} aria-invalid={isError} aria-describedby={describedBy} required />
      <label><input type="checkbox" name="policyApproved" value="yes" checked={values.policyApproved} onChange={(event) => update("policyApproved", event.target.checked)} aria-invalid={isError} aria-describedby={describedBy} /> Policy reviewed and approved</label>
      <label><input type="checkbox" name="enabled" value="yes" checked={values.enabled} disabled={manual} onChange={(event) => update("enabled", event.target.checked)} aria-invalid={isError} aria-describedby={describedBy} /> Enable for future retrieval</label>
      <button type="submit" disabled={pending}>Save Permitted Source</button>
    </form>
    <p id="permitted-sources-status" role="status" aria-live="polite" className={isError ? "status status-error" : "status"}>{error ? error.summary : state.summary}{error?.safeNextAction || state.safeNextAction ? <> <strong>Safe next action:</strong> {error?.safeNextAction ?? state.safeNextAction}</> : null}</p><p>Saving a source does not open it, test it, or retrieve jobs. For unknown or disallowed access, use the normal site page and manually import a selected listing.</p>
  </section>;
}
