import { createHash } from "node:crypto";

import { createAuditEvent, createUuidV7 } from "@/audit/audit-event";
import { captureOpportunityDraft } from "@/domain/opportunities/capture-draft";
import { WorkspaceError } from "@/domain/workspace/types";
import { resolveAppDataPaths } from "@/files/app-data";
import { applyMigrations, openDatabase } from "@/persistence/database";
import { findCapturedOpportunityByDuplicateKey, insertCapturedOpportunity, insertCapturedRevision, insertDuplicateSuggestion, listCapturedOpportunities as storedOpportunities, listCapturedRevisions } from "@/persistence/captured-opportunities-repository";
import { appendAuditEvent } from "@/persistence/workspace-repository";

type Options = { appDataRoot?: string };
export type ConfirmCapturedOpportunityInput = Options & { postingUrl: unknown; copiedDescription: unknown; title: unknown; company: unknown; location: unknown; workStyle: unknown; requirements: unknown; postedAt: unknown };
export type CapturedOpportunity = { id: string; title: string; company: string; location: string; workStyle: string; requirements: string[]; postedAt: string; capturedAt: string; revisions: Array<{ id: string; originalUrl: string; copiedDescription: string; contentDigest: string }> };
const digest = (value: unknown) => `sha256:${createHash("sha256").update(JSON.stringify(value)).digest("hex")}`;
const normalize = (value: unknown, field: string, code: "OPPORTUNITY_TITLE_INVALID" | "OPPORTUNITY_COMPANY_INVALID" | "OPPORTUNITY_LOCATION_INVALID" | "OPPORTUNITY_WORK_STYLE_INVALID" | "OPPORTUNITY_POSTED_DATE_INVALID", max: number) => { if (typeof value !== "string") throw new WorkspaceError(code, `Enter a valid ${field}.`, `Correct the ${field} and confirm again.`); const result = value.replace(/\s+/g, " ").trim(); if (!result || result.length > max) throw new WorkspaceError(code, `Enter a valid ${field}.`, `Correct the ${field} and confirm again.`); return result; };
function values(input: ConfirmCapturedOpportunityInput) { const draft = captureOpportunityDraft({ postingUrl: input.postingUrl, copiedDescription: input.copiedDescription }); const title = normalize(input.title, "title", "OPPORTUNITY_TITLE_INVALID", 300); const company = normalize(input.company, "company", "OPPORTUNITY_COMPANY_INVALID", 300); const location = normalize(input.location, "location", "OPPORTUNITY_LOCATION_INVALID", 300); const workStyle = normalize(input.workStyle, "work style", "OPPORTUNITY_WORK_STYLE_INVALID", 120); const requirements = typeof input.requirements === "string" ? input.requirements.split(/\r?\n/).map((value) => value.replace(/\s+/g, " ").trim()).filter(Boolean) : []; if (requirements.length < 1 || requirements.length > 20 || requirements.some((value) => value.length > 1000)) throw new WorkspaceError("OPPORTUNITY_REQUIREMENTS_INVALID", "Enter up to 20 plain-text requirements.", "Correct the requirements and confirm again."); const rawDate = normalize(input.postedAt, "posted date", "OPPORTUNITY_POSTED_DATE_INVALID", 40); const postedAt = rawDate === "Unknown" ? rawDate : (() => { if (!/^\d{4}-\d{2}-\d{2}$/.test(rawDate)) throw new WorkspaceError("OPPORTUNITY_POSTED_DATE_INVALID", "Enter a valid posted date or Unknown.", "Correct the posted date and confirm again."); const date = new Date(`${rawDate}T00:00:00.000Z`); if (Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== rawDate) throw new WorkspaceError("OPPORTUNITY_POSTED_DATE_INVALID", "Enter a valid posted date or Unknown.", "Correct the posted date and confirm again."); return date.toISOString(); })(); return { ...draft, title, company, location, workStyle, requirements, postedAt, duplicateKey: `${title.toLocaleLowerCase()}|${company.toLocaleLowerCase()}` }; }
function projection(db: ReturnType<typeof openDatabase>): { opportunities: CapturedOpportunity[] } { return { opportunities: storedOpportunities(db).map((opportunity) => { const revisions = listCapturedRevisions(db, opportunity.id); const latest = revisions.at(-1); if (!latest) throw new WorkspaceError("OPPORTUNITY_STORED_INVALID", "A saved opportunity cannot be read safely.", "Check local workspace storage, then try again."); return { id: opportunity.id, title: latest.title, company: latest.company, location: latest.location, workStyle: latest.workStyle, requirements: JSON.parse(latest.requirements) as string[], postedAt: latest.postedAt, capturedAt: latest.capturedAt, revisions: revisions.map((revision) => ({ id: revision.id, originalUrl: revision.originalUrl, copiedDescription: revision.copiedDescription, contentDigest: revision.contentDigest })) }; }) }; }
export async function listCapturedOpportunities(options: Options = {}) { const paths = await resolveAppDataPaths(options.appDataRoot); const db = openDatabase(paths.databasePath); try { applyMigrations(db); return projection(db); } finally { db.close(); } }
export async function confirmCapturedOpportunity(input: ConfirmCapturedOpportunityInput): Promise<{ opportunity: CapturedOpportunity; probableDuplicate: boolean }> { const item = values(input); const paths = await resolveAppDataPaths(input.appDataRoot); const db = openDatabase(paths.databasePath); try { applyMigrations(db); db.exec("BEGIN IMMEDIATE;"); try { const now = new Date().toISOString(); const opportunityId = createUuidV7(); const revisionId = createUuidV7(); const existing = findCapturedOpportunityByDuplicateKey(db, item.duplicateKey); const revisionDigest = digest({ opportunityId, capturedAt: item.capturedAt, originalUrl: item.postingUrl, copiedDescription: item.copiedDescription, title: item.title, company: item.company, location: item.location, workStyle: item.workStyle, requirements: item.requirements, postedAt: item.postedAt }); insertCapturedOpportunity(db, { id: opportunityId, duplicateKey: item.duplicateKey, createdAt: now }); insertCapturedRevision(db, { id: revisionId, opportunityId, capturedAt: item.capturedAt, originalUrl: item.postingUrl, copiedDescription: item.copiedDescription, title: item.title, company: item.company, location: item.location, workStyle: item.workStyle, requirements: JSON.stringify(item.requirements), postedAt: item.postedAt, contentDigest: revisionDigest, createdAt: now }); if (existing) insertDuplicateSuggestion(db, { id: createUuidV7(), opportunityId, probableDuplicateOpportunityId: existing.id, createdAt: now, contentDigest: digest({ opportunityId, probableDuplicateOpportunityId: existing.id }) }); appendAuditEvent(db, createAuditEvent({ actor: "local-os-user", action: "opportunity.captured", outcome: "success", entityId: opportunityId, contentHash: digest({ opportunityId, revisionId, capturedAt: item.capturedAt }) })); db.exec("COMMIT;"); const opportunity = projection(db).opportunities.find((candidate) => candidate.id === opportunityId)!; return { opportunity, probableDuplicate: Boolean(existing) }; } catch (error) { db.exec("ROLLBACK;"); throw error; } } finally { db.close(); } }
