import { createHash } from "node:crypto";
import { WorkspaceError } from "@/domain/workspace/types";

const endpoint = "http://127.0.0.1:1234/api/v1/chat";
const maxRequest = 20_000; const maxResponse = 12_000;
const plain = (value: unknown, maximum: number) => typeof value === "string" && value.length > 0 && value.length <= maximum && !/[\u0000-\u001f\u007f-\u009f]/.test(value);
const boundedText = (value: unknown, maximum: number) => typeof value === "string" && value.length > 0 && value.length <= maximum && !/[\u0000\u007f-\u009f]/.test(value);
const uuid = (value: unknown) => typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const sha = (value: unknown) => typeof value === "string" && /^sha256:[0-9a-f]{64}$/.test(value);
const exactKeys = (value: Record<string, unknown>, keys: string[]) => Object.keys(value).every((key) => keys.includes(key)) && keys.every((key) => key in value);
const supports = (claim: string, evidence: string[]) => { const words = (value: string) => new Set(value.toLocaleLowerCase().match(/[a-z0-9]{3,}/g) ?? []); const claimWords = words(claim); return evidence.some((item) => [...claimWords].filter((word) => words(item).has(word)).length >= 2); };

export type LocalModelConnection = { configurationRevisionId: string; configurationDigest: string; modelIdentifier: string; token: string };
export type ResumeCoachOpportunity = { revisionId: string; contentDigest: string; title: string; company: string; requirements: string[]; copiedDescription: string };
export type ResumeCoachRequest = { connection: LocalModelConnection; profileRevisionId: string; profileDigest: string; profileSnapshot: string; templateId: string; templateDigest: string; evidence: Array<{ id: string; contentDigest: string; factualText: string }>; opportunity?: ResumeCoachOpportunity; userRequest: string; consentNonce: string; consentFingerprint: string };
export type ResumeCoachResponse = { schemaVersion: 1; sections: Array<{ heading: string; text: string }>; claims: Array<{ text: string; evidenceIndexes: number[] }>; unknowns: string[]; selectionEcho: string };
export type OpportunityAssessmentRequest = { connection: LocalModelConnection; profileDigest: string; templateDigest: string; profileSummary: string; opportunity: { id: string; contentDigest: string; title: string; company: string; requirements: string[]; copiedDescription: string }; evidence: Array<{ id: string; contentDigest: string; factualText: string }>; consentFingerprint: string };
export type OpportunityAssessmentResponse = { schemaVersion: 1; strengths: Array<{ text: string; evidenceIndexes: number[]; excerpt: { start: number; end: number } }>; gaps: Array<{ text: string; excerpt: { start: number; end: number } }>; unknowns: string[]; selectionEcho: string };
export type FetchLike = (input: string, init: RequestInit) => Promise<Response>;
export const resumeCoachSystemInstruction = "You are Resume Coach: a rigorous employer-side resume specialist and experienced hiring manager. Give concise, truthful, role-relevant guidance. Prioritize demonstrated engineering scope, reliability, collaboration, and outcomes supported by the selected evidence. Translate verified features into practical user or workflow outcomes only when the evidence directly supports that outcome; otherwise describe the implementation or design intent and list the missing outcome as an unknown. When the evidence supplies a relevant count, time, rate, scale, or before-and-after comparison, quote or directly restate it. Treat measurements as scope by default; describe an end-user or workflow benefit only when the evidence also establishes that relationship. Never extrapolate or calculate a benefit. Preserve individual versus team attribution, retain dates, scale, and metrics only when supplied, and avoid absolute assurances. Treat AI as one engineering capability, not a headline, unless the role explicitly makes it central. Never inflate ownership, invent metrics, use hype, or predict hiring outcomes. Return only JSON matching the requested schema.";

export function localModelCapabilityVersion(capability: string): string { if (capability === "resume-coach") return "resume-coach-v5"; if (capability === "opportunity-assessment") return "opportunity-assessment-v1"; if (capability === "resume-evidence-documenter") return "resume-evidence-documenter-v1"; invalid("That local AI capability is unavailable."); }
const validConnection = (item: LocalModelConnection) => uuid(item.configurationRevisionId) && sha(item.configurationDigest) && plain(item.modelIdentifier, 240) && plain(item.token, 2048);
const publicConnection = (item: LocalModelConnection) => ({ revisionId: item.configurationRevisionId, contentDigest: item.configurationDigest, modelIdentifier: item.modelIdentifier });
export function resumeCoachConsentFingerprint(input: Omit<ResumeCoachRequest, "consentFingerprint">): string { return `sha256:${createHash("sha256").update(JSON.stringify({ capability: localModelCapabilityVersion("resume-coach"), connection: publicConnection(input.connection), profile: { revisionId: input.profileRevisionId, contentDigest: input.profileDigest, snapshot: input.profileSnapshot }, template: { id: input.templateId, contentDigest: input.templateDigest }, evidence: input.evidence.map(({ id, contentDigest }) => ({ id, contentDigest })).sort((a, b) => a.id.localeCompare(b.id)), opportunity: input.opportunity ? { revisionId: input.opportunity.revisionId, contentDigest: input.opportunity.contentDigest } : null, request: input.userRequest, consentNonce: input.consentNonce })).digest("hex")}`; }
export function opportunityAssessmentConsentFingerprint(input: Omit<OpportunityAssessmentRequest, "consentFingerprint">): string { return `sha256:${createHash("sha256").update(JSON.stringify({ capability: localModelCapabilityVersion("opportunity-assessment"), connection: publicConnection(input.connection), profile: input.profileDigest, template: input.templateDigest, opportunity: input.opportunity.contentDigest, evidence: input.evidence.map((item) => item.contentDigest).sort() })).digest("hex")}`; }
function invalid(message: string, next = "Review the selected material and try the local request again."): never { throw new WorkspaceError("RESUME_COACH_INVALID", message, next); }

function validCoach(request: ResumeCoachRequest) {
  const opportunity = request.opportunity; const validOpportunity = !opportunity || (uuid(opportunity.revisionId) && sha(opportunity.contentDigest) && plain(opportunity.title, 300) && plain(opportunity.company, 300) && plain(opportunity.copiedDescription, 20_000) && Array.isArray(opportunity.requirements) && opportunity.requirements.length > 0 && opportunity.requirements.length <= 20 && opportunity.requirements.every((item) => plain(item, 1_000)));
  if (!validConnection(request.connection) || !plain(request.userRequest, 2_000) || !plain(request.profileSnapshot, 4_000) || !plain(request.consentNonce, 128) || !uuid(request.profileRevisionId) || !sha(request.profileDigest) || !uuid(request.templateId) || !sha(request.templateDigest) || !sha(request.consentFingerprint) || !request.evidence.length || request.evidence.length > 50 || request.evidence.some((item) => !uuid(item.id) || !plain(item.factualText, 4_000) || !sha(item.contentDigest)) || !validOpportunity) invalid("The selected local material cannot be sent safely.");
  if (JSON.stringify({ ...request, connection: { ...request.connection, token: undefined } }).length > maxRequest || request.consentFingerprint !== resumeCoachConsentFingerprint(request)) invalid("The local-model consent is no longer current.", "Review the disclosure and submit the request again.");
}
function coachResponse(value: unknown, evidence: ResumeCoachRequest["evidence"], fingerprint: string): ResumeCoachResponse {
  if (!value || typeof value !== "object" || Array.isArray(value)) invalid("The local model returned an unusable response."); const item = value as Record<string, unknown>; const sections = item.sections; const claims = item.claims; const unknowns = item.unknowns;
  if (!exactKeys(item, ["schemaVersion", "selectionEcho", "sections", "claims", "unknowns"]) || item.schemaVersion !== 1 || item.selectionEcho !== fingerprint || !Array.isArray(sections) || !sections.length || sections.length > 8 || !Array.isArray(claims) || claims.length > 20 || !Array.isArray(unknowns) || unknowns.length > 12) invalid("The local model returned an unsafe or incomplete response.");
  if (sections.some((section) => !section || typeof section !== "object" || !exactKeys(section as Record<string, unknown>, ["heading", "text"]) || !plain((section as Record<string, unknown>).heading, 120) || !plain((section as Record<string, unknown>).text, 2_000)) || claims.some((claim) => !claim || typeof claim !== "object" || !exactKeys(claim as Record<string, unknown>, ["text", "evidenceIndexes"]) || !plain((claim as Record<string, unknown>).text, 1_000) || !Array.isArray((claim as Record<string, unknown>).evidenceIndexes) || !(claim as { evidenceIndexes: unknown[] }).evidenceIndexes.length || new Set((claim as { evidenceIndexes: unknown[] }).evidenceIndexes).size !== (claim as { evidenceIndexes: unknown[] }).evidenceIndexes.length || (claim as { evidenceIndexes: unknown[] }).evidenceIndexes.some((index) => !Number.isInteger(index) || (index as number) < 0 || (index as number) >= evidence.length) || !(claim as { text: string; evidenceIndexes: number[] }).evidenceIndexes.every((index) => supports((claim as { text: string }).text, [evidence[index]!.factualText]))) || unknowns.some((unknown) => !plain(unknown, 500))) invalid("The local model returned unsupported guidance.");
  const result = { schemaVersion: 1 as const, sections: sections as ResumeCoachResponse["sections"], claims: claims as ResumeCoachResponse["claims"], unknowns: unknowns as string[], selectionEcho: fingerprint }; if (JSON.stringify(result).length > maxResponse) invalid("The local model response is too large to review safely."); return result;
}
async function native(connection: LocalModelConnection, systemPrompt: string, input: unknown, maximumTokens: number, fetcher: FetchLike, code: "RESUME_COACH_UNAVAILABLE" | "OPPORTUNITY_ASSESSMENT_UNAVAILABLE" | "EVIDENCE_DOCUMENTER_INVALID"): Promise<unknown> {
  const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 30_000);
  try { const body = JSON.stringify({ model: connection.modelIdentifier, input: JSON.stringify(input), system_prompt: systemPrompt, stream: false, store: false, temperature: 0.2, max_output_tokens: maximumTokens }); if (body.length > maxRequest) throw new WorkspaceError(code, "The selected local material cannot be sent safely.", "Review the selected local material and try again."); const result = await fetcher(endpoint, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${connection.token}` }, body, signal: controller.signal }); if (!result.ok || Number(result.headers.get("content-length") ?? 0) > maxResponse * 2) throw new Error("unavailable"); const raw = await result.text(); if (raw.length > maxResponse * 2) throw new WorkspaceError(code, "The local model returned an oversized response.", "Try the local request again after the model is ready."); const parsed = JSON.parse(raw) as { response_id?: unknown; output?: unknown; stats?: { model_load_time_seconds?: unknown } }; if (parsed.response_id !== undefined || parsed.stats?.model_load_time_seconds !== undefined || !Array.isArray(parsed.output) || parsed.output.length !== 1) throw new WorkspaceError(code, "The local model returned an unsafe stateful response.", "Try the local request again after the model is ready."); const message = parsed.output[0] as { type?: unknown; content?: unknown }; if (!message || message.type !== "message" || !boundedText(message.content, maxResponse)) throw new WorkspaceError(code, "The local model returned an unusable response.", "Try the local request again after the model is ready."); return JSON.parse(String(message.content)); } catch (error) { if (error instanceof WorkspaceError) throw error; throw new WorkspaceError(code, "Local AI is unavailable right now.", "Confirm LM Studio is running locally with the configured model, then try again."); } finally { clearTimeout(timeout); }
}
export async function requestResumeCoach(request: ResumeCoachRequest, fetcher: FetchLike = fetch): Promise<ResumeCoachResponse> { validCoach(request); return coachResponse(await native(request.connection, resumeCoachSystemInstruction, { schemaVersion: 1, selectionEcho: request.consentFingerprint, profile: request.profileSnapshot, templateDigest: request.templateDigest, evidence: request.evidence.map(({ factualText, contentDigest }) => ({ factualText, contentDigest })), opportunity: request.opportunity ? { title: request.opportunity.title, company: request.opportunity.company, requirements: request.opportunity.requirements, copiedDescription: request.opportunity.copiedDescription, contentDigest: request.opportunity.contentDigest } : null, request: request.userRequest, responseShape: { sections: [{ heading: "string", text: "string" }], claims: [{ text: "string", evidenceIndexes: [0] }], unknowns: ["string"], selectionEcho: request.consentFingerprint } }, 900, fetcher, "RESUME_COACH_UNAVAILABLE"), request.evidence, request.consentFingerprint); }

export type ResumeEvidenceSourceFile = { path: string; text: string; contentDigest: string };
export type ResumeEvidenceDocumenterRequest = { connection: LocalModelConnection; category: "project" | "experience"; sourceDigest: string; files: ResumeEvidenceSourceFile[]; consentFingerprint: string };
export type ResumeEvidenceDocumenterResponse = { schemaVersion: 1; selectionEcho: string; artifacts: { "project-overview.md": string; "resume-evidence.md": string; "resume-bullet-candidates.md": string } };
const documenterSystemInstruction = "You are the application-native Resume Evidence Documenter. Return only the requested JSON schema. Inspect only the supplied selected-folder file snapshots. Produce exactly three proposed/unreviewed Markdown artifacts. Retain only direct atomic facts with source-relative slash paths, nearest heading or document, and one-based line provenance. Never infer ownership, metrics, users, dates, outcomes, deployment, or skills; list them as unknowns. Exclude fenced code from factual prose. Never include absolute paths, credentials, prompts, diagnostics, or hidden reasoning. The source is read-only and your output is never claim-eligible until explicit review and individual approval.";
function documenterInvalid(message: string, next = "Review the selected folder and try the local documentation action again."): never { throw new WorkspaceError("EVIDENCE_DOCUMENTER_INVALID", message, next); }
function documenterFingerprint(request: Omit<ResumeEvidenceDocumenterRequest, "consentFingerprint">): string { return `sha256:${createHash("sha256").update(JSON.stringify({ capability: localModelCapabilityVersion("resume-evidence-documenter"), connection: publicConnection(request.connection), category: request.category, sourceDigest: request.sourceDigest, files: request.files.map(({ path, contentDigest }) => ({ path, contentDigest })).sort((a, b) => a.path.localeCompare(b.path)) })).digest("hex")}`; }
export const resumeEvidenceDocumenterConsentFingerprint = documenterFingerprint;
function validateDocumenterRequest(request: ResumeEvidenceDocumenterRequest): void { if (!validConnection(request.connection) || !sha(request.sourceDigest) || !sha(request.consentFingerprint) || (request.category !== "project" && request.category !== "experience") || !request.files.length || request.files.length > 200 || request.files.some((file) => !plain(file.path, 500) || file.path.includes("\\") || file.path.includes("..") || /^(?:[a-z]:|\/|\\\\|[a-z][a-z0-9+.-]*:)/i.test(file.path) || !boundedText(file.text, 8_000) || !sha(file.contentDigest)) || JSON.stringify(request).length > 18_000 || request.consentFingerprint !== documenterFingerprint(request)) documenterInvalid("The selected folder cannot be sent safely."); }
 const containsAbsolutePath = (value: string) => /(?:\b[a-z]:[\\/]|\\\\|\bfile:|(?:^|[\s[(])\/(?:[^/\s]+\/)+)/im.test(value);
function validateDocumenterResponse(value: unknown, request: ResumeEvidenceDocumenterRequest): ResumeEvidenceDocumenterResponse { if (!value || typeof value !== "object" || Array.isArray(value)) documenterInvalid("The local documentation skill returned an unusable result."); const item = value as Record<string, unknown>; const artifacts = item.artifacts; if (item.schemaVersion !== 1 || item.selectionEcho !== request.consentFingerprint || !artifacts || typeof artifacts !== "object" || Array.isArray(artifacts) || !exactKeys(artifacts as Record<string, unknown>, ["project-overview.md", "resume-evidence.md", "resume-bullet-candidates.md"])) documenterInvalid("The local documentation skill returned an incomplete result."); const output = artifacts as Record<string, unknown>; if (Object.values(output).some((text) => !boundedText(text, 12_000) || !/Proposed \/ Unreviewed/i.test(text as string) || containsAbsolutePath(text as string))) documenterInvalid("The local documentation skill returned unsafe review artifacts."); return { schemaVersion: 1, selectionEcho: request.consentFingerprint, artifacts: output as ResumeEvidenceDocumenterResponse["artifacts"] }; }
export async function requestResumeEvidenceDocumentation(request: ResumeEvidenceDocumenterRequest, fetcher: FetchLike = fetch): Promise<ResumeEvidenceDocumenterResponse> { validateDocumenterRequest(request); const result = await native(request.connection, documenterSystemInstruction, { schemaVersion: 1, selectionEcho: request.consentFingerprint, category: request.category, sourceDigest: request.sourceDigest, files: request.files.map(({ path, text }) => ({ path, text })), responseShape: { schemaVersion: 1, selectionEcho: request.consentFingerprint, artifacts: { "project-overview.md": "string", "resume-evidence.md": "string", "resume-bullet-candidates.md": "string" } } }, 3_600, fetcher, "EVIDENCE_DOCUMENTER_INVALID"); return validateDocumenterResponse(result, request); }

function assessmentInvalid(message: string, next = "Review the selected opportunity material and try the assessment again."): never { throw new WorkspaceError("OPPORTUNITY_ASSESSMENT_INVALID", message, next); }
export function validateOpportunityAssessmentResponse(value: unknown, request: OpportunityAssessmentRequest): OpportunityAssessmentResponse { if (!value || typeof value !== "object" || Array.isArray(value)) assessmentInvalid("The local model returned an unusable assessment."); const item = value as Record<string, unknown>; const strengths = item.strengths; const gaps = item.gaps; const unknowns = item.unknowns; const excerpt = (value: unknown) => { if (!value || typeof value !== "object") return false; const range = value as { start?: unknown; end?: unknown }; return Number.isInteger(range.start) && Number.isInteger(range.end) && (range.start as number) >= 0 && (range.end as number) > (range.start as number) && (range.end as number) <= request.opportunity.copiedDescription.length && (range.end as number) - (range.start as number) <= 500; }; const predicts = (text: unknown) => typeof text === "string" && /\b(hired|hire|interview|offer|employer intent|will get)\b/i.test(text); if (item.schemaVersion !== 1 || item.selectionEcho !== request.consentFingerprint || !Array.isArray(strengths) || strengths.length > 12 || !Array.isArray(gaps) || gaps.length > 12 || !Array.isArray(unknowns) || unknowns.length > 12 || strengths.some((entry) => !entry || typeof entry !== "object" || !plain((entry as { text?: unknown }).text, 900) || predicts((entry as { text?: unknown }).text) || !excerpt((entry as { excerpt?: unknown }).excerpt) || !Array.isArray((entry as { evidenceIndexes?: unknown }).evidenceIndexes) || !(entry as { evidenceIndexes: unknown[] }).evidenceIndexes.length || (entry as { evidenceIndexes: unknown[] }).evidenceIndexes.some((index) => !Number.isInteger(index) || (index as number) < 0 || (index as number) >= request.evidence.length)) || gaps.some((entry) => !entry || typeof entry !== "object" || !plain((entry as { text?: unknown }).text, 900) || predicts((entry as { text?: unknown }).text) || !excerpt((entry as { excerpt?: unknown }).excerpt)) || unknowns.some((entry) => !plain(entry, 500) || predicts(entry))) assessmentInvalid("The local model returned unsafe assessment guidance."); const result = { schemaVersion: 1 as const, strengths: strengths as OpportunityAssessmentResponse["strengths"], gaps: gaps as OpportunityAssessmentResponse["gaps"], unknowns: unknowns as string[], selectionEcho: request.consentFingerprint }; if (JSON.stringify(result).length > maxResponse) assessmentInvalid("The local model assessment is too large to review safely."); return result; }
export async function requestOpportunityAssessment(request: OpportunityAssessmentRequest, fetcher: FetchLike = fetch): Promise<OpportunityAssessmentResponse> { if (!validConnection(request.connection) || !plain(request.profileSummary, 4_000) || !sha(request.profileDigest) || !sha(request.templateDigest) || !plain(request.opportunity.id, 64) || !sha(request.opportunity.contentDigest) || !plain(request.opportunity.copiedDescription, 20_000) || !request.opportunity.requirements.length || request.opportunity.requirements.length > 20 || request.opportunity.requirements.some((item) => !plain(item, 1_000)) || !request.evidence.length || request.evidence.length > 50 || request.evidence.some((item) => !plain(item.id, 64) || !plain(item.factualText, 4_000) || !sha(item.contentDigest)) || request.consentFingerprint !== opportunityAssessmentConsentFingerprint(request)) assessmentInvalid("The selected local assessment material cannot be sent safely."); return validateOpportunityAssessmentResponse(await native(request.connection, "Return only JSON. Assess semantic resume-to-opportunity fit using supplied evidence. Never predict hiring, interviews, offers, or employer intent.", { schemaVersion: 1, selectionEcho: request.consentFingerprint, profile: request.profileSummary, opportunity: { title: request.opportunity.title, company: request.opportunity.company, requirements: request.opportunity.requirements, copiedDescription: request.opportunity.copiedDescription }, evidence: request.evidence.map(({ factualText, contentDigest }) => ({ factualText, contentDigest })), responseShape: { strengths: [{ text: "string", evidenceIndexes: [0], excerpt: { start: 0, end: 1 } }], gaps: [{ text: "string", excerpt: { start: 0, end: 1 } }], unknowns: ["string"], selectionEcho: request.consentFingerprint } }, 1100, fetcher, "OPPORTUNITY_ASSESSMENT_UNAVAILABLE"), request); }
