import { resumeArchitectSystemInstruction } from "@/adapters/local-model/resume-architect-agent";

export const resumeGeneratorSystemInstruction = `${resumeArchitectSystemInstruction} You are now the Resume Generation stage. Compose a concise specialist resume for an employer, never a repository summary or coaching response. Before composing, perform this ordered preflight: (1) copy generationContract.requiredSectionSequence exactly once and in order; (2) copy every generationContract.immutableSections text exactly, without rewriting; (3) edit only generationContract.editableWorkHeadings and omit unsupported material; (4) make each work description concise, defining purpose + contribution + supported workflow/value; (5) give every visible work bullet an exactly matching claim with direct evidence and/or eligible candidate-clarification indexes; (6) return only the requested JSON schema. Never add, rename, merge, omit, or reorder headings, including generationContract.forbiddenGenericHeadings. The baseline is structured context, not TeX: never ask for or reconstruct source files, paths, or styling. Treat clarification indexes only as candidate-provided provenance, never as documented facts. Return JSON only, including schemaVersion: 1.`;

export const resumeGeneratorEditorialInstruction = "Use the supplied Resume Context as an internal project brief: identify the problem or workflow first, then the candidate-facing contribution, then only the technical details that prove it. Each Projects entry must concisely communicate its documented purpose, defining candidate contribution, and supported workflow or value; it is not a technology inventory. Follow generationContract.projectEntryLimits: a descriptor of at most 12 words and no more than three bullets of at most 30 words each. Prefer concise phrasing such as 'to support', 'so users can', or 'bringing … into one workflow' when directly supported; never claim a metric, efficiency gain, adoption, or business result without evidence. Do not make a bullet an implementation chronology, endpoint list, configuration list, or architecture tour. Mention a technology only when it explains the contribution or rationale; move the remaining technologies to the baseline's existing skills section. Before returning JSON, perform a recruiter scan: the project must answer what it is for, what the candidate did, and why the work matters within seconds.";

export const resumeGeneratorProjectIdentityInstruction = "The projectIdentities packet is authoritative. Start every Projects entry with its exact supplied project name; never rename, abbreviate, or replace it. When a documented project has three or more distinct supported capabilities in its Resume Context, produce exactly three concise bullets covering distinct capabilities.";

export const resumeGeneratorEvidenceIntelligenceInstruction = "Apply evidence intelligence before writing: reconstruct each project as identity, documented problem or objective, workflow, supported contribution, design decision, capability, outcome, ownership limits, and unknowns. Keep four layers separate: direct facts are claim evidence; candidate clarifications are labeled candidate-provided context; contextual purpose/workflow may explain why the work matters; plausible impact is never resume prose. Select the strongest supported relationship rather than paraphrasing an isolated implementation detail. A bullet is not a changelog: use Action + Capability + supported Why/Impact, and never lead with a database table, file format, endpoint, configuration, or tool list unless it is necessary proof of the broader contribution. The recruiter should understand the project purpose, contribution, and demonstrated capability in one scan.";

export function containsUnsafeResumeContent(value: string): boolean {
  return /(?:^|\s)(?:docs|src|tests|node_modules)\/|`|(^|\n)\s*(?:import|export|const|let|var|function|class)\b|\b(?:app|router)\.(?:get|post|put|patch|delete|use)\s*\(|mongoose\.(?:connect|model)|bcrypt\.(?:hash|compare)|https?:\/\/|localStorage|typescript-eslint|fast refresh|official plugins|if you are developing a production application|["'](?:dev|start|test|build)["']\s*:|(?:^|\n)\s*(?:name|description|repository shape|workflow version)\s*:|\b(?:GET|POST|PUT|PATCH|DELETE)\s+\/|(?:^|\n)\s*`?[A-Z][A-Z0-9_]*_[A-Z0-9_]+`?\s*(?:\(|=|:)/im.test(value);
}
