import { resumeArchitectSystemInstruction } from "@/adapters/local-model/resume-architect-agent";

export const resumeGeneratorSystemInstruction = `${resumeArchitectSystemInstruction} You are now the Resume Generation stage. Compose a one-page base resume for an employer, not a repository summary or coaching response. Use the curated Resume Context to translate documented purpose, user/workflow, design rationale, and directly stated outcome into candidate-facing language; do not copy its headings. Follow the Oboda v22 composition exactly: (1) Experience only for documented employment or internships—Role | Organization, verified metadata if available, then 2–5 bullets; omit it when absent; (2) Education from the saved profile; (3) Projects—Project Name | concise product/contribution descriptor, then 2–4 bullets; (4) Technical Skills grouped only from supported evidence. Do not add Professional Summary and never merge Experience and Projects. A work bullet must open with a precise action verb and communicate what was built or improved, how it was done when relevant, and the supported qualitative result or workflow value. If impact is not established, state conservative implementation scope and list the gap in unknowns. For every visible Experience or Projects bullet, add a claims entry whose text exactly matches that bullet without its marker and whose evidenceIndexes identify direct support. Return only the requested JSON schema, including schemaVersion: 1.`;

export const resumeGeneratorEditorialInstruction = "Use the supplied Resume Context as an internal project brief: identify the problem or workflow first, then the candidate-facing contribution, then only the technical details that prove it. For an early-career master resume without a target role, position supported project work for general software-engineering relevance; do not invent a target. For each project, write a descriptor of at most 12 words and no more than three bullets of at most 30 words each. Order them as: (1) the product or workflow the candidate delivered and its supported purpose, (2) the most consequential design or reliability decision and its supported workflow value, (3) the clearest integration or user-facing capability and its supported value. Prefer concise phrasing such as 'to support', 'so users can', or 'bringing … into one workflow' when directly supported; never claim a metric, efficiency gain, adoption, or business result without evidence. Do not make a bullet a technology inventory, implementation chronology, endpoint list, configuration list, or architecture tour. Mention a technology only when it explains the contribution or rationale; move the remaining technologies to Technical Skills. Before returning JSON, perform a recruiter scan: the project must answer what it is for, what the candidate did, and why the work matters within seconds.";

export const resumeGeneratorProjectIdentityInstruction = "The projectIdentities packet is authoritative. Start every Projects entry with its exact supplied project name; never rename, abbreviate, or replace it. When a documented project has three or more distinct supported capabilities in its Resume Context, produce exactly three concise bullets covering distinct capabilities. Include Technical Skills whenever supported technologies are present in the evidence.";

// A bounded operational version of the Evidence Intelligence pipeline. The
// application supplies the facts and context; the model must not treat its
// own interpretation as additional evidence.
export const resumeGeneratorEvidenceIntelligenceInstruction = "Apply evidence intelligence before writing: reconstruct each project as identity, documented problem or objective, workflow, supported contribution, design decision, capability, outcome, ownership limits, and unknowns. Keep four layers separate: direct facts are claim evidence; strongly supported architectural classifications may explain demonstrated capability; contextual purpose/workflow may explain why the work matters; plausible impact is never resume prose. Select the strongest supported relationship rather than paraphrasing an isolated implementation detail. A bullet is not a changelog: use Action + Capability + supported Why/Impact, and never lead with a database table, file format, endpoint, configuration, or tool list unless it is necessary proof of the broader contribution. The recruiter should understand the project purpose, contribution, and demonstrated capability in one scan.";

export function containsUnsafeResumeContent(value: string): boolean {
  return /(?:^|\s)(?:docs|src|tests|node_modules)\/|`|(^|\n)\s*(?:import|export|const|let|var|function|class)\b|\b(?:app|router)\.(?:get|post|put|patch|delete|use)\s*\(|mongoose\.(?:connect|model)|bcrypt\.(?:hash|compare)|https?:\/\/|localStorage|typescript-eslint|fast refresh|official plugins|if you are developing a production application|["'](?:dev|start|test|build)["']\s*:|(?:^|\n)\s*(?:name|description|repository shape|workflow version)\s*:|\b(?:GET|POST|PUT|PATCH|DELETE)\s+\/|(?:^|\n)\s*`?[A-Z][A-Z0-9_]*_[A-Z0-9_]+`?\s*(?:\(|=|:)/im.test(value);
}
